"""The E2 launcher must be correct before the E1 gate opens, not after.

``run_phase_confirmation.py`` refuses to run as ``__main__`` and names this
launcher as the only execution path, so a defect here is discovered at exactly
the moment the screen closes and E2 is supposed to start.
"""

import json
from pathlib import Path

import pytest
import yaml

import scripts.modal_phase_confirmation as mpc

AXES = {
    "degree_rewire": {"rates": [0.0, 0.25, 1.0], "perturbation_seed": 31415},
    "feature_mask": {"rates": [0.0, 1.0], "perturbation_seed": 14142},
}


@pytest.fixture
def gated(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """A generated confirmation config plus the sealed baseline it points at."""
    baseline = {
        "data_fingerprint_sha256": "abc123def456789012345678",
        "baseline": {"selected_gnn": {"parameters": {"parameters": 213506}}},
        "config": {
            "data": "/root/message-passing-retrieval/storage/data/webqsp",
            "topology_cache": "/root/clean/topology",
            "feature_cache": "/root/clean/features",
        },
    }
    sealed = tmp_path / "outputs" / "sa_mlp_confirmation"
    sealed.mkdir(parents=True)
    (sealed / "webqsp.json").write_text(json.dumps(baseline), encoding="utf-8")

    config = {
        "modal": {"app": mpc.APP_NAME},
        "axes": AXES,
        "datasets": {
            "webqsp": {
                "expected_queries": 1578,
                "selected_gnn": "gat",
                "confirmation": "outputs/sa_mlp_confirmation/webqsp.json",
            }
        },
        "training": {
            "seeds": [0, 1, 2, 3, 4],
            "epochs": 3,
            "batch_size": 16,
            "learning_rate": 0.001,
            "weight_decay": 0.0001,
            "ks": [1, 5, 20],
        },
        "parameter_regime": {"hidden_dim": 64, "maximum_sa_absolute_difference": 256},
        "inference_repeats": 5,
    }
    config_path = tmp_path / "phase_confirmation.yaml"
    config_path.write_text(yaml.safe_dump(config), encoding="utf-8")
    monkeypatch.setattr(mpc, "CONFIRMATION_CONFIG_PATH", config_path)
    monkeypatch.setattr(mpc, "HOST_REPO_ROOT", tmp_path)
    return config_path


def test_launching_before_the_gate_is_refused_with_an_explanation(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # The config is generated by the screen analysis. Absent it, there are no
    # selected rates, and inventing any would break the validation-only rule.
    monkeypatch.setattr(mpc, "CONFIRMATION_CONFIG_PATH", tmp_path / "absent.yaml")
    with pytest.raises(SystemExit) as excinfo:
        mpc._jobs(["webqsp"])
    assert "analyze_phase_screen.py" in str(excinfo.value)


def test_the_clean_rate_never_becomes_a_confirmation_cell(gated: Path) -> None:
    # run_phase_confirmation refuses rate <= 0: the clean condition reuses the
    # sealed confirmation instead of being retrained. The merged rate set
    # always contains 0.0, so the launcher has to drop it or every launch
    # fails on its first clean cell.
    jobs = mpc._jobs(["webqsp"])
    assert jobs, "no cells built"
    assert all(job["rate"] > 0.0 for job in jobs)
    assert len(jobs) == 3  # 0.25 and 1.0 on degree_rewire, 1.0 on feature_mask


def test_each_cell_points_at_its_own_screen_result(gated: Path) -> None:
    # E2 reuses the seed-0 validation checkpoint from the matching screen cell.
    # Pointing at another cell would silently confirm the wrong rate.
    for job in mpc._jobs(["webqsp"]):
        args = mpc._runner_args(job)
        regime = f"{job['axis']}_{mpc._rate_key(job['rate'])}"
        assert args.screen_result.as_posix().endswith(
            f"outputs/phase_screen/webqsp/abc123def4567890/{regime}/result.json"
        )
        assert regime in args.output.as_posix()
        assert args.output.as_posix().startswith(f"{mpc.STORAGE_ROOT}/outputs/phase_confirmation")


def test_every_cell_runs_the_full_registered_seed_set(gated: Path) -> None:
    # The runner refuses to finish a cell whose seed set is incomplete, and a
    # confirmation on fewer seeds is not the registered five-seed design.
    for job in mpc._jobs(["webqsp"]):
        assert mpc._runner_args(job).seeds == [0, 1, 2, 3, 4]


def test_a_config_naming_a_different_app_is_refused(
    gated: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    # Deploying under one app while the config names another would leave the
    # results unfindable by anything that reads the config.
    config = yaml.safe_load(gated.read_text(encoding="utf-8"))
    config["modal"]["app"] = "message-passing-retrieval-phase-screen"
    gated.write_text(yaml.safe_dump(config), encoding="utf-8")
    with pytest.raises(SystemExit, match="names app"):
        mpc._jobs(["webqsp"])


def test_the_launcher_deploys_the_app_the_analysis_generates() -> None:
    # analyze_phase_screen.py writes this app name into the config it emits.
    analyzer = (
        Path(__file__).resolve().parents[1] / "scripts" / "analyze_phase_screen.py"
    ).read_text(encoding="utf-8")
    assert f'"app": "{mpc.APP_NAME}"' in analyzer
