#!/usr/bin/env python
"""Compile the five-seed phase-crossover confirmation (Package E2).

The registered contract lives in the generated ``configs/phase_confirmation.yaml``
and is applied here rather than restated: primary contrast
``seed_aware_gnn_minus_sa_mlp_recall_at_5``, paired over seed and query, Holm
scope ``datasets_within_axis_and_rate``, every selected cell reported.

Two properties separate this package from Package C and are asserted rather than
assumed. First, no perturbation axis touches candidate generation: the axes move
edges or node features, so within a dataset the candidate pool -- and therefore
the Recall@K ceiling -- is identical at every rate. A change in the gap across
rates consequently cannot be produced by a moving ceiling, which is exactly the
confound that governs the budget results. Second, the rate under test was
selected from validation alone; each cell carries that assertion and a cell that
does not is refused rather than reported.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

import numpy as np
import yaml

from scripts.analyze_linear_rank_structure import (
    _hierarchical_paired_ci,
    _holm,
    _mean_std_ci,
    _paired_t_pvalue,
)

REPO_ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = REPO_ROOT / "configs" / "phase_confirmation.yaml"
MODEL_NAMES = ("sa_mlp", "seed_aware_gnn")
METRICS = ("recall@1", "recall@5", "recall@20", "mrr", "full_coverage@20")
PRIMARY_METRIC = "recall@5"
CELL_COMPLETE = "PHASE_CONFIRMATION_CELL_COMPLETE"
SEALED_COMPLETE = "SA_MLP_CONFIRMATION_DATASET_COMPLETE"
CLEAN_RATE = 0.0

GATE_MESSAGE = (
    "configs/phase_confirmation.yaml does not exist. The confirmation matrix is "
    "generated by scripts/analyze_phase_screen.py from validation outcomes only. "
    "Run the screen analysis first; do not hand-write the selected rates."
)


def _rate_key(rate: float) -> str:
    return f"{rate:.2f}".replace(".", "p")


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _load_arrays(
    path: Path,
    expected_sha256: str,
    expected_order_sha256: str,
    seeds: list[int],
) -> dict[str, np.ndarray]:
    """Per-query metrics for both models, verified against the recorded hashes.

    The result records the container-side path of this file; only its digest
    travels, so the digest is what is checked.
    """
    if _sha256(path) != expected_sha256:
        raise ValueError(f"Phase-confirmation query metrics failed SHA-256: {path}")
    with np.load(path) as packed:
        if tuple(map(str, packed["metric_names"].tolist())) != METRICS:
            raise ValueError(f"Phase-confirmation metric order changed: {path}")
        if str(packed["query_order_sha256"].item()) != expected_order_sha256:
            raise ValueError(f"Phase-confirmation query order changed: {path}")
        return {
            model: np.stack(
                [
                    np.asarray(packed[f"{model}_seed_{seed}"], dtype=np.float32)
                    for seed in seeds
                ]
            )
            for model in MODEL_NAMES
        }


def _cell_source(
    root: Path,
    dataset: str,
    axis: str,
    rate: float,
    sealed_root: Path,
) -> tuple[dict[str, Any], Path]:
    """The result and packed metrics for one cell.

    The clean rate is not an E2 cell: retraining it would produce a second,
    non-identical clean condition, so every axis reuses the one sealed five-seed
    confirmation as its shared origin.
    """
    if rate == CLEAN_RATE:
        payload = json.loads((sealed_root / f"{dataset}.json").read_text(encoding="utf-8"))
        if payload.get("status") != SEALED_COMPLETE:
            raise ValueError(f"{dataset} sealed clean confirmation is not complete")
        return payload, sealed_root / f"{dataset}.query_metrics.npz"
    cell = root / dataset / axis / f"rate_{_rate_key(rate)}"
    payload = json.loads((cell / "result.json").read_text(encoding="utf-8"))
    return payload, cell / "query_metrics.npz"


def _verify_cell(
    payload: dict[str, Any],
    dataset: str,
    axis: str,
    rate: float,
) -> None:
    if rate == CLEAN_RATE:
        return
    label = f"{dataset}/{axis}/rate_{_rate_key(rate)}"
    if payload.get("status") != CELL_COMPLETE:
        raise ValueError(f"{label} is not complete")
    if payload.get("dataset") != dataset or payload.get("axis") != axis:
        raise ValueError(f"{label} has a different contract")
    if float(payload.get("rate", -1)) != rate:
        raise ValueError(f"{label} records a different rate")
    contract = payload.get("confirmation_contract", {})
    # The claim the package rests on. A missing assertion is not compliance.
    if contract.get("test_selected_rate") is not False:
        raise ValueError(
            f"{label} does not assert that its rate was selected without test outcomes"
        )
    if contract.get("selected_by_locked_validation_only_rule") is not True:
        raise ValueError(f"{label} does not assert the locked rule")
    if (
        contract.get("seed_zero_validation_checkpoint_reused_without_test_peeking")
        is not True
    ):
        raise ValueError(f"{label} does not assert seed-0 provenance")


def compile_analysis(
    root: Path,
    *,
    sealed_root: Path,
    bootstrap_replicates: int = 2000,
    bootstrap_seed: int = 20260901,
) -> dict[str, Any]:
    if not CONFIG_PATH.is_file():
        raise SystemExit(GATE_MESSAGE)
    config = yaml.safe_load(CONFIG_PATH.read_text(encoding="utf-8"))
    seeds = list(map(int, config["training"]["seeds"]))
    rows: list[dict[str, Any]] = []

    for dataset_position, dataset in enumerate(sorted(config["datasets"])):
        for axis_position, axis in enumerate(sorted(config["axes"])):
            for rate_position, rate in enumerate(
                sorted(map(float, config["axes"][axis]["rates"]))
            ):
                payload, packed_path = _cell_source(root, dataset, axis, rate, sealed_root)
                _verify_cell(payload, dataset, axis, rate)
                arrays = _load_arrays(
                    packed_path,
                    payload["query_metrics"]["sha256"],
                    payload["data"]["test_query_order_sha256"],
                    seeds,
                )
                low, high = _hierarchical_paired_ci(
                    arrays["seed_aware_gnn"],
                    arrays["sa_mlp"],
                    replicates=bootstrap_replicates,
                    seed=bootstrap_seed
                    + dataset_position * 1009
                    + axis_position * 101
                    + rate_position,
                )
                models = {
                    model: {
                        metric: _mean_std_ci(
                            [
                                float(
                                    payload["models"][model]["seeds"][str(seed)]["metrics"][
                                        metric
                                    ]
                                )
                                for seed in seeds
                            ]
                        )
                        for metric in METRICS
                    }
                    for model in MODEL_NAMES
                }
                difference = {}
                for metric_index, metric in enumerate(METRICS):
                    by_seed = [
                        float(
                            payload["models"]["seed_aware_gnn"]["seeds"][str(seed)][
                                "metrics"
                            ][metric]
                        )
                        - float(
                            payload["models"]["sa_mlp"]["seeds"][str(seed)]["metrics"][metric]
                        )
                        for seed in seeds
                    ]
                    difference[metric] = {
                        "seed_effect": _mean_std_ci(by_seed),
                        "paired_seed_t_pvalue": _paired_t_pvalue(by_seed),
                        "paired_hierarchical_query_ci95_low": float(low[metric_index]),
                        "paired_hierarchical_query_ci95_high": float(high[metric_index]),
                    }
                rows.append(
                    {
                        "dataset": dataset,
                        "axis": axis,
                        "rate": rate,
                        "is_clean_origin": rate == CLEAN_RATE,
                        "models": models,
                        "seed_aware_gnn_minus_sa_mlp": difference,
                    }
                )

    # Holm within one axis and rate, across datasets: the registered scope.
    for axis in sorted(config["axes"]):
        for rate in sorted(map(float, config["axes"][axis]["rates"])):
            cell_rows = [row for row in rows if row["axis"] == axis and row["rate"] == rate]
            for metric in METRICS:
                adjusted = _holm(
                    {
                        row["dataset"]: row["seed_aware_gnn_minus_sa_mlp"][metric][
                            "paired_seed_t_pvalue"
                        ]
                        for row in cell_rows
                    }
                )
                for row in cell_rows:
                    row["seed_aware_gnn_minus_sa_mlp"][metric]["holm_pvalue"] = adjusted[
                        row["dataset"]
                    ]

    return {
        "status": "PHASE_CONFIRMATION_ALL_CELLS_ANALYZED",
        "primary_metric": PRIMARY_METRIC,
        "seeds": seeds,
        "bootstrap": {"replicates": bootstrap_replicates, "seed": bootstrap_seed},
        "holm_scope": "datasets_within_axis_and_rate",
        "claims": {
            "candidate_pool_constant_across_rates": (
                "No axis touches candidate generation, so within a dataset every "
                "rate shares one candidate pool and one Recall@K ceiling. A change "
                "in the gap across rates cannot be a ceiling effect."
            ),
            "rates_selected_without_test_outcomes": (
                "Every cell asserts test_selected_rate false, the locked "
                "validation-only rule, and seed-0 checkpoint provenance; a cell "
                "that does not is refused rather than reported."
            ),
            "clean_origin_shared": (
                "The clean rate is the one sealed five-seed confirmation, reused by "
                "every axis rather than retrained per axis."
            ),
        },
        "rows": rows,
    }


def _crossings(analysis: dict[str, Any]) -> list[dict[str, Any]]:
    """Rate intervals where the primary gap changes sign within one dataset-axis.

    A sign change is reported as significant only when both endpoints are
    individually Holm-significant, so a crossing is not manufactured out of two
    cells that are each indistinguishable from zero.
    """
    found = []
    for dataset in sorted({row["dataset"] for row in analysis["rows"]}):
        for axis in sorted({row["axis"] for row in analysis["rows"]}):
            series = sorted(
                (
                    row
                    for row in analysis["rows"]
                    if row["dataset"] == dataset and row["axis"] == axis
                ),
                key=lambda row: row["rate"],
            )
            for left, right in zip(series, series[1:]):
                before = left["seed_aware_gnn_minus_sa_mlp"][PRIMARY_METRIC]
                after = right["seed_aware_gnn_minus_sa_mlp"][PRIMARY_METRIC]
                before_mean = before["seed_effect"]["mean"]
                after_mean = after["seed_effect"]["mean"]
                if (before_mean < 0 < after_mean) or (after_mean < 0 < before_mean):
                    found.append(
                        {
                            "dataset": dataset,
                            "axis": axis,
                            "interval": [left["rate"], right["rate"]],
                            "gap_before": before_mean,
                            "gap_after": after_mean,
                            "both_endpoints_holm_significant": bool(
                                before["holm_pvalue"] < 0.05
                                and after["holm_pvalue"] < 0.05
                            ),
                        }
                    )
    return found


def _fmt(value: float) -> str:
    return f"{100.0 * value:+.2f}"


def render_markdown(analysis: dict[str, Any]) -> str:
    lines = [
        "# Five-seed phase-crossover confirmation",
        "",
        f"Status: **{analysis['status']}**. Primary contrast: seed-aware GNN minus "
        f"QLS-MLP on {PRIMARY_METRIC}, in points. Seeds: "
        f"{', '.join(map(str, analysis['seeds']))}. Holm correction is applied across "
        "datasets within one axis and rate.",
        "",
        "Every rate was selected from validation outcomes alone, before any test "
        "metric existed for these cells. No perturbation axis touches candidate "
        "generation, so within a dataset the candidate pool and the Recall@K "
        "ceiling are identical at every rate: unlike the budget package, nothing "
        "here can be explained by a moving ceiling.",
        "",
    ]

    datasets = sorted({row["dataset"] for row in analysis["rows"]})
    for axis in sorted({row["axis"] for row in analysis["rows"]}):
        lines.append(f"## {axis}")
        lines.append("")
        lines.append(
            "| Dataset | Rate | GNN R@5 | QLS R@5 | GNN-QLS | query CI95 | Holm p |"
        )
        lines.append("|---|---:|---:|---:|---:|---|---:|")
        for dataset in datasets:
            series = sorted(
                (
                    row
                    for row in analysis["rows"]
                    if row["dataset"] == dataset and row["axis"] == axis
                ),
                key=lambda row: row["rate"],
            )
            for row in series:
                gap = row["seed_aware_gnn_minus_sa_mlp"][PRIMARY_METRIC]
                label = f"{row['rate']:.2f}" + (" (clean)" if row["is_clean_origin"] else "")
                lines.append(
                    f"| {dataset} | {label} "
                    f"| {100.0 * row['models']['seed_aware_gnn'][PRIMARY_METRIC]['mean']:.2f} "
                    f"| {100.0 * row['models']['sa_mlp'][PRIMARY_METRIC]['mean']:.2f} "
                    f"| {_fmt(gap['seed_effect']['mean'])} "
                    f"| [{_fmt(gap['paired_hierarchical_query_ci95_low'])}, "
                    f"{_fmt(gap['paired_hierarchical_query_ci95_high'])}] "
                    f"| {gap['holm_pvalue']:.4f} |"
                )
        lines.append("")

    crossings = _crossings(analysis)
    lines.append("## Sign changes in the primary contrast")
    lines.append("")
    if not crossings:
        lines.append(
            "No dataset-axis series changes the sign of the gap. The registered "
            "crossover prediction is not supported by these cells."
        )
    else:
        confirmed = [row for row in crossings if row["both_endpoints_holm_significant"]]
        lines.append(
            f"{len(crossings)} rate interval(s) change sign; {len(confirmed)} of them "
            "have both endpoints individually Holm-significant. Only the latter are "
            "evidence of a crossover: a sign change between two cells that are each "
            "indistinguishable from zero is a change in noise, not in regime."
        )
        lines.append("")
        lines.append(
            "| Dataset | Axis | Interval | Gap before | Gap after | Both ends significant |"
        )
        lines.append("|---|---|---|---:|---:|---|")
        for row in crossings:
            lines.append(
                f"| {row['dataset']} | {row['axis']} "
                f"| {row['interval'][0]:.2f} to {row['interval'][1]:.2f} "
                f"| {_fmt(row['gap_before'])} | {_fmt(row['gap_after'])} "
                f"| {'yes' if row['both_endpoints_holm_significant'] else 'no'} |"
            )
    lines.append("")
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root", type=Path, default=REPO_ROOT / "outputs" / "phase_confirmation"
    )
    parser.add_argument(
        "--sealed-root", type=Path, default=REPO_ROOT / "outputs" / "sa_mlp_confirmation"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=REPO_ROOT / "outputs" / "phase_confirmation_analysis.json",
    )
    parser.add_argument(
        "--markdown", type=Path, default=REPO_ROOT / "docs" / "PHASE_CONFIRMATION_RESULTS.md"
    )
    parser.add_argument("--bootstrap-replicates", type=int, default=2000)
    parser.add_argument("--bootstrap-seed", type=int, default=20260901)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    analysis = compile_analysis(
        args.root,
        sealed_root=args.sealed_root,
        bootstrap_replicates=args.bootstrap_replicates,
        bootstrap_seed=args.bootstrap_seed,
    )
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(analysis, indent=2), encoding="utf-8")
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.write_text(render_markdown(analysis), encoding="utf-8")
    print(
        json.dumps({"status": analysis["status"], "cells": len(analysis["rows"])}, indent=2)
    )


if __name__ == "__main__":
    main()
