"""Modal launcher for the M2D Stage-0 semantic diagnostic.

CPU only, zero GPU hours authorised. Four spawned jobs, one per declared cell,
each reading the frozen data volume, M2's sealed cell masters and BOTH of M2B's
sealed semantic checkpoints, and writing only under M2D's own output prefix.
Nothing is trained, no weight is fitted, and no test split is opened.

Submit through scripts/spawn_modal_jobs.py so the run is server-side; a
detached local run is not a registered execution.

Two rungs, not one, is the difference from M2C's launcher. M2D compares S4
against the incumbent S3 and asks what each finds that the other misses, so the
S3 checkpoint is loaded here alongside S4's. Loading it is not a re-selection:
S3 remains M2B's frozen choice and S4 remains a development challenger, and the
fusion arm that scores both together is carried as DIAGNOSTIC ONLY because
running two semantic models is not an eligible system.

The container shape is not decided here. It is read from the compute record
filed before this launcher was allowed to run -- generated by
scripts/m2d_stage0_compute_record.py -- so a job cannot quietly acquire an
accelerator or a larger box than the filed prediction priced, and the spend
gate in spawn_modal_jobs.py prices the shape the container will actually hold
rather than a training phase's GPU default.

The declared cells, the arms and the authorisation all come from
configs/m2d_s4_semantic_repair.yaml. This file restates none of them: a
launcher holding its own copy of the matrix can only ever disagree with the
thing that declared it.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path, PurePosixPath
from typing import Any

import modal
import yaml

REMOTE_ROOT = "/root/message-passing-retrieval"
HOST_REPO_ROOT = Path(__file__).resolve().parents[1]
RUNTIME_REPO_ROOT = (
    HOST_REPO_ROOT
    if (HOST_REPO_ROOT / "configs" / "m2d_s4_semantic_repair.yaml").is_file()
    else Path(REMOTE_ROOT)
)
M2D_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "m2d_s4_semantic_repair.yaml"
M2_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "m2_qls_v2_freeze.yaml"
M1A_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "m1a_feature_screen.yaml"
CONFIRMATION_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "sa_mlp_confirmation.yaml"
COMPUTE_RECORD_PATH = (
    RUNTIME_REPO_ROOT / "outputs" / "m2d_s4_semantic_repair" / "stage0_compute_record.json"
)

M2D_CONFIG_TEXT = M2D_CONFIG_PATH.read_text(encoding="utf-8")
CONFIG = yaml.safe_load(M2D_CONFIG_TEXT)
M2_CONFIG = yaml.safe_load(M2_CONFIG_PATH.read_text(encoding="utf-8"))
M1A_CONFIG = yaml.safe_load(M1A_CONFIG_PATH.read_text(encoding="utf-8"))
CONFIRMATION_CONFIG = yaml.safe_load(CONFIRMATION_CONFIG_PATH.read_text(encoding="utf-8"))

#: The declaration's text, so every artifact this launch produces can say which
#: version of the protocol it was run under. Computed from the file rather than
#: from the parsed mapping: a comment that changes what a rule means changes the
#: fingerprint, which is the behaviour a provenance field should have. Over the
#: DECODED text rather than the raw bytes, because the host reads this file with
#: CRLF and the container reads it with LF, and one declaration must not have
#: two fingerprints depending on which side asked.
CONFIG_FINGERPRINT = hashlib.sha256(M2D_CONFIG_TEXT.encode("utf-8")).hexdigest()

#: The four declared cells, read from the declaration. One dataset each, which
#: is what lets a job be addressed by dataset the way every other launcher in
#: this track is; a fifth cell on an already-listed dataset would break that,
#: and is refused here rather than discovered as an overwritten result.
_CELL_BLOCK = CONFIG["stage_0"]["cells"]
CELLS: dict[str, str] = {}
for _cell in (
    *_CELL_BLOCK["failure_cells"],
    _CELL_BLOCK["passage_control"],
    _CELL_BLOCK["kb_control"],
):
    _dataset, _regime = _cell.split("/")
    if _dataset in CELLS:
        raise RuntimeError(
            f"{_dataset} carries two declared Stage-0 cells; this launcher spawns one "
            "job per dataset and the second would overwrite the first"
        )
    CELLS[_dataset] = _regime

# spawn_modal_jobs.py's shared package protocol validates --datasets against
# module.CONFIG["datasets"]. The alias satisfies that contract without adding a
# datasets key to the declaration's own schema.
CONFIG["datasets"] = CELLS

#: The container shape the compute record filed, taken from the declaration's
#: own copy of it. The generated record and this block are held equal by a
#: declaration test; this is the copy that is committed, and -- decisively --
#: the copy that exists inside the container, because the image carries src/,
#: scripts/ and configs/ and no outputs/ tree. The decorator below is evaluated
#: remotely as well as locally, so it can only read from something the container
#: has.
SHAPE = CONFIG["launch_authorization"]["stage_0_compute_record"]
if SHAPE["gpu"] is not None or SHAPE["gpu_hours_authorised"]:
    raise RuntimeError("M2D Stage 0 authorises zero GPU hours; refusing to hold one")

# Copied, not aliased: M2D must not be able to change M1A's or M2's infra view.
# The infra keys -- volume, storage root, execution label -- stay M1A's, because
# they name where the frozen artifacts actually are. The SHAPE keys are
# overwritten from the filed record, because M1A's are a training phase's
# (A10G, 16 cores, 48 GiB, 24 h) and pricing a forward-pass probe at them would
# report a spend the declaration never authorised.
MODAL_CONFIG = dict(M1A_CONFIG["modal"])
GPU = SHAPE["gpu"]
CPU = int(SHAPE["cpu"])
MEMORY_MB = int(SHAPE["memory_mb"])
TIMEOUT_SECONDS = int(SHAPE["timeout_seconds"])
MODAL_CONFIG.update(
    {"gpu": GPU, "cpu": CPU, "memory_mb": MEMORY_MB, "timeout_seconds": TIMEOUT_SECONDS}
)

STORAGE_ROOT = MODAL_CONFIG["storage_root"]
APP_NAME = "message-passing-retrieval-m2d-stage0-probe"
OUTPUT_PREFIX = "m2d_s4_semantic_repair"
M2_OUTPUT_PREFIX = "m2_qls_v2_freeze"

#: The frozen build key of the cell stores M2 sealed. M2D reads it; it never
#: sets it. Section 1 freezes the scored universe, and these are the fields
#: that identify it.
BUILD_KEY = M2_CONFIG["qls_universal"]["hyperparameters"]
M2B_OUTPUT_PREFIX = "m2b_semantic_minimality"

#: The rungs whose weights Stage 0 reads, and the directories M2B stored them
#: in. M2B writes ``fit_root = cell_root / rung.lower()``, so the two differ in
#: case; on the container's filesystem that difference is a missing file.
RUNGS = ("S4", "S3")

#: One cell is one spawned call that writes its result once, at the end. A
#: restart therefore redoes exactly one cell and no more.
#: spawn_modal_jobs.py reads this to decide whether the piece a restart redoes
#: is one job or the whole probe; silence there is costed as no resumption.
RESUME_GRANULARITY = "cell"

app = modal.App(APP_NAME)
result_volume = modal.Volume.from_name(MODAL_CONFIG["result_volume"], create_if_missing=False)
image = (
    modal.Image.micromamba(python_version="3.11")
    .env(
        {
            "CONDA_OVERRIDE_CUDA": "12.1",
            "CUDA_HOME": "/opt/conda",
            "TORCH_CUDA_ARCH_LIST": "8.6",
            "PYTHONPATH": f"{REMOTE_ROOT}:{REMOTE_ROOT}/src",
        }
    )
    .apt_install("git", "build-essential", "ninja-build")
    .pip_install(
        "torch==2.2.1",
        "numpy<2.0",
        "scipy<1.14",
        "numba==0.60.0",
        "psutil==6.1.1",
        "pyyaml==6.0.2",
    )
    .pip_install(
        "torch-geometric==2.5.2",
        "torch-scatter==2.1.2",
        "torch-sparse==0.6.18",
        find_links="https://data.pyg.org/whl/torch-2.2.1+cu121.html",
    )
    .add_local_dir(str(RUNTIME_REPO_ROOT / "src"), remote_path=f"{REMOTE_ROOT}/src")
    .add_local_dir(str(RUNTIME_REPO_ROOT / "scripts"), remote_path=f"{REMOTE_ROOT}/scripts")
    .add_local_dir(str(RUNTIME_REPO_ROOT / "configs"), remote_path=f"{REMOTE_ROOT}/configs")
)


def compute_record() -> dict[str, Any]:
    """The filed Stage-0 compute record. Host-side only, and read on demand.

    On demand rather than at import because this module is imported inside the
    container too -- Modal loads it there to find ``run_stage0`` -- and the
    image carries no ``outputs/`` tree, so an import-time read would make every
    remote job die at startup. It is also read on demand so the module stays
    importable on a fresh clone, where the record has not been generated yet:
    the registry test imports every launcher, and a launcher that cannot be
    imported without a gitignored artifact is a launcher nobody can check.

    Absence is still refused at the moment it matters, in
    ``require_authorisation``, which is where a launch is actually decided.
    """

    if not COMPUTE_RECORD_PATH.is_file():
        raise SystemExit(
            f"{COMPUTE_RECORD_PATH} does not exist. A filed compute record is a "
            "precondition of this launch; regenerate it with "
            "scripts/m2d_stage0_compute_record.py before submitting."
        )
    record = json.loads(COMPUTE_RECORD_PATH.read_text(encoding="utf-8"))
    if not record.get("filed_before_any_job_was_submitted"):
        raise SystemExit(f"{COMPUTE_RECORD_PATH} is not a pre-launch record")
    if record["container"]["gpu"] is not None or not record.get("authorises_no_gpu"):
        raise SystemExit("the filed record authorises zero GPU hours; refusing to hold one")
    container = record["container"]
    declared = (GPU, CPU, MEMORY_MB, TIMEOUT_SECONDS)
    filed = (
        container["gpu"],
        int(container["cpu_cores"]),
        int(container["memory_mb"]),
        int(container["timeout_seconds"]),
    )
    if declared != filed:
        raise SystemExit(
            f"the declaration's container shape {declared} and the filed record's "
            f"{filed} disagree. They are written by one script; regenerate rather "
            "than reconcile them by hand."
        )
    priced = {item["cell"] for item in record["workload"]["cells"]}
    declared_cells = {f"{dataset}/{regime}" for dataset, regime in CELLS.items()}
    if priced != declared_cells:
        raise SystemExit(
            f"the filed record prices {sorted(priced)} and the declaration names "
            f"{sorted(declared_cells)}. A job nobody priced is a job nobody authorised."
        )
    return record


def _host_commit() -> str | None:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(HOST_REPO_ROOT),
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):  # pragma: no cover
        return None


def _validation_split_queries(dataset: str, confirmation: dict[str, Any]) -> int:
    """This dataset's validation split size, derived then cross-checked.

    The same derivation M2, M2B and M2C used, and for the same reason: Stage 0
    loads M2's sealed cell master under its build key, so it has to ask for the
    identical panel M2 scored. A different number here fails that check, which
    is the correct outcome but a wasteful way to find a transcription error.
    """

    measured = int(confirmation["data"]["splits"]["validation"])
    declared = M1A_CONFIG["datasets"].get(dataset, {}).get("validation_split_queries")
    if declared is not None and int(declared) != measured:
        raise ValueError(
            f"{dataset}: configs/m1a_feature_screen.yaml declares validation_split_queries="
            f"{declared} but its confirmation artifact's validation split holds {measured} "
            "queries -- resolve this before launching; Stage 0 reads M2's cell master for "
            "that split and cannot rebuild it"
        )
    return measured


def _m2_fits_root(dataset: str, fingerprint: str) -> PurePosixPath:
    """Where M2's headline run left this dataset's cell masters. Read-only.

    Masters live at ``<root>/<regime>/cell_features``, the layout
    run_m2_qls_v2_freeze.py wrote.
    """

    return (
        PurePosixPath(STORAGE_ROOT)
        / "outputs"
        / M2_OUTPUT_PREFIX
        / dataset
        / fingerprint[:16]
        / MODAL_CONFIG["execution_label"]
        / "headline"
        / "fits"
    )


def _m2b_fits_root(dataset: str, fingerprint: str) -> PurePosixPath:
    """Where M2B left this dataset's semantic checkpoints. Read-only.

    Checkpoints live at ``<root>/<regime>/<rung.lower()>/checkpoint.pt``, the
    layout run_m2b_semantic_minimality.py wrote -- lowercased, which is why the
    rungs are not spelled here as the declaration spells them.
    """

    return (
        PurePosixPath(STORAGE_ROOT)
        / "outputs"
        / M2B_OUTPUT_PREFIX
        / dataset
        / fingerprint[:16]
        / MODAL_CONFIG["execution_label"]
        / "headline"
        / "fits"
    )


def _jobs(datasets: list[str]) -> list[dict[str, Any]]:
    unknown = set(datasets) - set(CELLS)
    if unknown:
        raise ValueError(
            f"{sorted(unknown)} are not M2D Stage-0 cells; the declaration names "
            f"{sorted(CELLS)} and no others"
        )
    commit = _host_commit()
    jobs = []
    for dataset in datasets:
        settings = CONFIRMATION_CONFIG["datasets"][dataset]
        confirmation_path = HOST_REPO_ROOT / f"outputs/sa_mlp_confirmation/{dataset}.json"
        confirmation = json.loads(confirmation_path.read_text(encoding="utf-8"))
        if confirmation.get("status") != "SA_MLP_CONFIRMATION_DATASET_COMPLETE":
            raise ValueError(f"{confirmation_path} is not a complete confirmation artifact")
        fingerprint = confirmation["data_fingerprint_sha256"]
        jobs.append(
            {
                "dataset": dataset,
                "regime": CELLS[dataset],
                "fingerprint": fingerprint,
                "data_remote": confirmation["config"]["data"],
                "baseline": confirmation["baseline"],
                "expected_queries": int(confirmation["config"]["expected_queries"]),
                "validation_split_queries": _validation_split_queries(dataset, confirmation),
                "candidate_contract_compatibility": settings.get(
                    "candidate_contract_compatibility"
                ),
                "m2_fits_remote": str(_m2_fits_root(dataset, fingerprint)),
                "m2b_fits_remote": str(_m2b_fits_root(dataset, fingerprint)),
                "config_fingerprint": CONFIG_FINGERPRINT,
                "source_commit": commit,
            }
        )
    return jobs


def _active_modal_profile() -> str | None:
    """The profile this client will actually submit under, or None if unreadable.

    None rather than a guess, and the caller refuses on it: the wrong answer
    here sends a job to the wrong workspace, and a Modal volume lives in
    exactly one workspace.
    """

    from_env = os.environ.get("MODAL_PROFILE")
    if from_env:
        return from_env
    try:
        from modal.config import _profile
    except ImportError:  # pragma: no cover - modal always ships this
        return None
    return _profile or None


def execution_placement() -> dict[str, str]:
    """Which workspace each dataset runs on, from M2's declaration and only there.

    Inheriting is the point here rather than a shortcut. Stage 0 reads M2's cell
    masters and M2B's checkpoints, so a dataset can only be probed from the
    workspace whose volume holds them -- the one M2 ran it on. The map moves as
    workspaces reach their spend limits, so a second copy could only ever go
    stale; M2D declares no placement of its own for exactly that reason, and a
    copy appearing there later is refused rather than silently preferred.
    """

    copied = CONFIG.get("launch_authorization", {}).get("execution_placement")
    if copied:
        raise SystemExit(
            "configs/m2d_s4_semantic_repair.yaml has grown its own execution_placement. "
            "The map is declared once, in configs/m2_qls_v2_freeze.yaml, and read at "
            "submit time; delete the copy."
        )
    inherited = M2_CONFIG["launch_authorization"].get("execution_placement")
    if not inherited:
        raise SystemExit(
            "configs/m2_qls_v2_freeze.yaml declares no workspace for these datasets; "
            "a dataset with no declared workspace cannot be submitted to one"
        )
    return dict(inherited)


def check_execution_placement(datasets: list[str]) -> dict[str, Any]:
    """Refuse to submit a dataset under a workspace its sealed artifacts are not on.

    scripts/spawn_modal_jobs.py calls this by name if a launcher defines it, so
    the check runs before the app is deployed and before anything is spawned.
    Stage 0 cannot rebuild a missing cell master or refit a missing checkpoint,
    so a misplaced job fails only after its container has started and been
    billed, having proved nothing.

    It is also where the declaration's gates are checked, because this is the
    only hook the server-side submission path calls before it deploys. A gate
    that only ``main`` consulted would be a gate the declared submission route
    walks straight past.
    """

    require_authorisation()
    placement = execution_placement()
    active = _active_modal_profile()
    if active is None:
        raise SystemExit(
            "cannot read the active Modal profile, so the workspace a job would land "
            "in is unknown. Set MODAL_PROFILE before importing modal."
        )
    undeclared = sorted(set(datasets) - set(placement))
    if undeclared:
        raise SystemExit(
            f"{undeclared} have no declared workspace in "
            "configs/m2_qls_v2_freeze.yaml#launch_authorization.execution_placement"
        )
    misplaced = {
        dataset: placement[dataset] for dataset in datasets if placement[dataset] != active
    }
    if misplaced:
        raise SystemExit(
            f"active profile {active!r} is not where these datasets' sealed artifacts "
            f"live: {misplaced}. Submit each dataset under its declared workspace."
        )
    return {"active_profile": active, "datasets": {d: placement[d] for d in datasets}}


def require_authorisation() -> None:
    """The declaration's gates, checked at call time rather than at import.

    At call time so this module stays importable -- and testable -- whatever the
    gates currently say, which is this track's standing order: commit the
    mechanism before the authorisation.
    """

    authorisation = CONFIG["launch_authorization"]
    if not authorisation["gates"].get("stage_0_compute_record_filed"):
        raise SystemExit(
            "configs/m2d_s4_semantic_repair.yaml has not recorded a filed Stage-0 "
            "compute record. The record is the gate on this launch."
        )
    authorised = " ".join(authorisation["authorised"]).lower()
    for required in ("complementarity", "rrf", "error-conditioned"):
        if required not in authorised:
            raise SystemExit(
                f"the declaration does not authorise the {required} diagnostic this "
                "launcher spawns; refusing to submit"
            )
    forbidden = {item.lower() for item in authorisation["not_authorised"]}
    if "seeds 1 and 2" not in forbidden or "the full 14-cell m2d screen" not in forbidden:
        raise SystemExit(
            "the declaration no longer restricts M2D to the seed-0 Stage-0 cells, so "
            "this launcher can no longer assume the four jobs it spawns are the whole "
            "authorised workload"
        )
    # Last, because it is the expensive one and because its failure message is
    # about regenerating an artifact rather than about authorisation.
    compute_record()


def _output_root(job: dict[str, Any]) -> PurePosixPath:
    """The run store this cell's artifact is written INTO, not the artifact path.

    run_artifacts derives the rest -- phase, dataset, regime, arm, commit and
    run id -- so two submissions of the same cell cannot address one file.
    """

    return (
        PurePosixPath(STORAGE_ROOT)
        / "outputs"
        / OUTPUT_PREFIX
        / "stage0"
        / job["dataset"]
        / job["fingerprint"][:16]
        / MODAL_CONFIG["execution_label"]
    )


def _runner_args(job: dict[str, Any]) -> argparse.Namespace:
    # The family A64 is defined on, and the value M2 recorded in this cell's
    # build key. Imported the way M2's own launcher imports it, and imported
    # rather than typed for a blunt reason: a different string here does not
    # mislabel the arm, it makes the sealed cell master refuse to load.
    from scripts.run_m0b_regime_map import MAINLINE_FAMILY

    regime = job["regime"]
    m2b_root = Path(job["m2b_fits_remote"]) / regime
    return argparse.Namespace(
        data=Path(job["data_remote"]),
        dataset=job["dataset"],
        regime=regime,
        data_fingerprint_sha256=job["fingerprint"],
        expected_queries=int(job["expected_queries"]),
        # The panel M2 scored, so the sealed master loads under its own build key.
        queries=int(job["validation_split_queries"]),
        baseline=job["baseline"],
        candidate_contract_compatibility=job["candidate_contract_compatibility"],
        cell_features=Path(job["m2_fits_remote"]) / regime / "cell_features",
        s4_checkpoint=m2b_root / "s4" / "checkpoint.pt",
        s3_checkpoint=m2b_root / "s3" / "checkpoint.pt",
        output_root=Path(_output_root(job)),
        config_fingerprint=job["config_fingerprint"],
        source_commit=job["source_commit"],
        run_id=None,
        holdout_fraction=0.2,
        dropout=0.2,
        temperature=0.07,
        panel_cap=0,
        # M2's frozen build key, read from its declaration rather than typed
        # here. These three decide whether the sealed master loads at all.
        per_seed_cap=int(BUILD_KEY["per_seed_cap"]),
        neighbour_scan_cap_per_seed=int(BUILD_KEY["neighbour_scan_cap_per_seed"]),
        a64_mainline_family=MAINLINE_FAMILY,
    )


@app.function(
    image=image,
    volumes={STORAGE_ROOT: result_volume},
    timeout=TIMEOUT_SECONDS,
    cpu=CPU,
    memory=MEMORY_MB,
)
def run_stage0(job: dict[str, Any]) -> dict[str, Any]:
    os.chdir(REMOTE_ROOT)
    # Load-bearing: M2's masters and M2B's checkpoints were written by other
    # containers in other phases, so without this the volume view is whatever
    # it was when this container started.
    result_volume.reload()
    from scripts.run_m2d_stage0_probe import run

    args = _runner_args(job)
    result = run(args)
    result_volume.commit()
    return {
        "status": result["status"],
        "dataset": job["dataset"],
        "cell": result["cell"],
        "queries": result["panel"]["queries"],
        "trained_anything": result["trained_anything"],
        "test_split_read": result["test_split_read"],
        "output_remote": result["artifact"]["path"],
    }


def _download(remote_path: str, local_path: Path) -> None:
    local_path.parent.mkdir(parents=True, exist_ok=True)
    relative = remote_path.removeprefix(f"{STORAGE_ROOT}/")
    with local_path.open("wb") as stream:
        for chunk in result_volume.read_file(relative):
            stream.write(chunk)


def _artifact_names() -> tuple[str, str, str]:
    """The phase, arm and filename run_artifacts will have used.

    Imported here rather than at module scope on purpose. This module is
    imported inside the container as well as on the host, and only the fetch
    path needs the probe's constants; a module-level import would drag the
    whole scoring stack into every container at startup for the sake of two
    strings.
    """

    for path in (HOST_REPO_ROOT, HOST_REPO_ROOT / "src"):
        if str(path) not in sys.path:
            sys.path.insert(0, str(path))
    from mp_retrieval.run_artifacts import ARTIFACT_FILENAME
    from scripts.run_m2d_stage0_probe import ARM, PHASE

    return PHASE, ARM, ARTIFACT_FILENAME


def _remote_prefix(job: dict[str, Any]) -> PurePosixPath:
    """The logical result's directory on the volume, above the physical runs.

    ``<phase>/<dataset>/<regime>/<seed>/<arm>`` -- run_artifacts orders its
    segments coarse to fine precisely so this prefix is listable. What lies
    under it is one directory per commit, and one per run inside that.
    """

    phase, arm, _ = _artifact_names()
    return _output_root(job) / phase / job["dataset"] / job["regime"] / "no_seed" / arm


def _remote_artifacts(prefix: PurePosixPath) -> list[str]:
    _, _, filename = _artifact_names()
    relative = str(prefix).removeprefix(f"{STORAGE_ROOT}/")
    found = []
    for entry in result_volume.listdir(relative, recursive=True):
        if PurePosixPath(entry.path).name == filename:
            found.append(f"{STORAGE_ROOT}/{entry.path}")
    return sorted(found)


def fetch(
    datasets: str = ",".join(CELLS), expect_source_commit: str = ""
) -> list[dict[str, Any]]:
    """Copy the selected result for each cell down beside the declaration.

    Separate from the spawn because the spawn is server-side and returns as
    soon as the calls are registered. Reads the volume; writes nothing to it.

    The artifact path carries a run id the host did not choose, so the store is
    listed rather than guessed. Every physical run found is downloaded and
    verified, and then ONE is selected as the logical result -- by commit,
    stated by the caller, never by whichever file is newest. That is the whole
    point of the persistence work: a run that did not land leaves an older
    run's numbers in place, and a fetcher that took the newest file would
    report them without noticing.
    """

    if not expect_source_commit:
        raise SystemExit(
            "fetch needs the commit whose run is being reported. Selecting between "
            "physical runs is a decision, and a fetch that picked for itself would "
            "be free to report a run that was never meant to stand."
        )
    requested = [name.strip() for name in datasets.split(",") if name.strip()]
    fetched = []
    local_root = HOST_REPO_ROOT / "outputs" / OUTPUT_PREFIX / "stage0"
    staging = local_root / "runs"
    for job in _jobs(requested):
        cell = f"{job['dataset']}/{job['regime']}"
        remotes = _remote_artifacts(_remote_prefix(job))
        if not remotes:
            raise RuntimeError(f"{cell}: the volume holds no artifact under its prefix")
        from mp_retrieval import run_artifacts

        receipts = []
        for remote in remotes:
            local = staging / PurePosixPath(remote).relative_to(STORAGE_ROOT)
            _download(remote, local)
            receipts.append(run_artifacts.verify_artifact_file(local))
        selected = run_artifacts.select_logical_result(
            receipts, expect_source_commit=expect_source_commit
        )
        destination = local_root / f"{job['dataset']}_{job['regime']}.json"
        destination.write_bytes(Path(selected.path).read_bytes())
        fetched.append(
            {
                "dataset": job["dataset"],
                "cell": cell,
                "local": str(destination),
                "source_commit": selected.identity.source_commit,
                "run_id": selected.identity.run_id,
                "rows": selected.rows,
                "physical_runs_found": len(receipts),
            }
        )
    return fetched


@app.local_entrypoint()
def main(datasets: str = ",".join(CELLS)) -> None:
    """A local fallback only. The declared submission path is server-side.

    scripts/spawn_modal_jobs.py deploys the app and spawns each job so the run
    outlives the client; this entrypoint exists so the app is complete and
    exercisable, and it refuses under the same gates.
    """

    requested = [name.strip() for name in datasets.split(",") if name.strip()]
    check_execution_placement(requested)
    results = list(run_stage0.map(_jobs(requested), return_exceptions=True))
    failures = [item for item in results if isinstance(item, BaseException)]
    if failures:
        raise RuntimeError(f"{len(failures)} M2D Stage-0 job(s) failed: {failures}")
    for result in results:
        _download(
            result["output_remote"],
            HOST_REPO_ROOT
            / "outputs"
            / OUTPUT_PREFIX
            / "stage0"
            / f"{result['cell'].replace('/', '_')}.json",
        )
    print(json.dumps(results, indent=2))
