"""Modal launcher for the M2C Stage-0 probe.

CPU only, zero GPU hours authorised. Four spawned jobs, one per declared cell,
each reading the frozen data volume, M2's sealed cell masters and M2B's sealed
S4 checkpoint, and writing only under M2C's own output prefix. Nothing is
trained, no weight is fitted, and no test split is opened.

Submit through scripts/spawn_modal_jobs.py so the run is server-side; a
detached local run is not a registered execution.

The container shape is not decided here. It is read from the compute record
filed before this launcher was allowed to run -- generated by
scripts/m2c_stage0_compute_record.py -- so a job cannot quietly acquire an
accelerator or a larger box than the filed prediction priced, and the spend
gate in spawn_modal_jobs.py prices the shape the container will actually hold
rather than M1A's GPU default.

The declared cells, the arms and the authorisation all come from
configs/m2c_s4_structural_conditioning.yaml. This file restates none of them: a
launcher holding its own copy of the matrix can only ever disagree with the
thing that declared it.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
from pathlib import Path, PurePosixPath
from typing import Any

import modal
import yaml

REMOTE_ROOT = "/root/message-passing-retrieval"
HOST_REPO_ROOT = Path(__file__).resolve().parents[1]
RUNTIME_REPO_ROOT = (
    HOST_REPO_ROOT
    if (HOST_REPO_ROOT / "configs" / "m2c_s4_structural_conditioning.yaml").is_file()
    else Path(REMOTE_ROOT)
)
M2C_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "m2c_s4_structural_conditioning.yaml"
M2_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "m2_qls_v2_freeze.yaml"
M1A_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "m1a_feature_screen.yaml"
CONFIRMATION_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "sa_mlp_confirmation.yaml"
COMPUTE_RECORD_PATH = (
    RUNTIME_REPO_ROOT
    / "outputs"
    / "m2c_s4_structural_conditioning"
    / "stage0_compute_record.json"
)

CONFIG = yaml.safe_load(M2C_CONFIG_PATH.read_text(encoding="utf-8"))
M2_CONFIG = yaml.safe_load(M2_CONFIG_PATH.read_text(encoding="utf-8"))
M1A_CONFIG = yaml.safe_load(M1A_CONFIG_PATH.read_text(encoding="utf-8"))
CONFIRMATION_CONFIG = yaml.safe_load(CONFIRMATION_CONFIG_PATH.read_text(encoding="utf-8"))

#: The four declared cells, read from the declaration. One dataset each, which
#: is what lets a job be addressed by dataset the way every other launcher in
#: this track is; a fifth cell on an already-listed dataset would break that,
#: and is refused here rather than discovered as an overwritten result.
_CELL_BLOCK = CONFIG["stage_0"]["cells"]
CELLS: dict[str, str] = {}
for _cell in (
    *_CELL_BLOCK["failure_cells"],
    _CELL_BLOCK["passage_r3_control"],
    _CELL_BLOCK["kb_r3_control"],
):
    _dataset, _regime = _cell.split("/")
    if _dataset in CELLS:
        raise RuntimeError(
            f"{_dataset} carries two declared Stage-0 cells; this launcher spawns one "
            "job per dataset and the second would overwrite the first"
        )
    CELLS[_dataset] = _regime

# spawn_modal_jobs.py's shared package protocol validates --datasets against
# module.CONFIG["datasets"]. The alias satisfies that contract without adding a
# datasets key to the declaration's own schema.
CONFIG["datasets"] = CELLS

#: The container shape the compute record filed, taken from the declaration's
#: own copy of it. The generated record and this block are written by the same
#: script and a declaration test holds them equal; this is the copy that is
#: committed, and -- decisively -- the copy that exists inside the container,
#: because the image carries src/, scripts/ and configs/ and no outputs/ tree.
#: The decorator below is evaluated remotely as well as locally, so it can only
#: read from something the container has.
SHAPE = CONFIG["launch_authorization"]["stage_0_compute_record"]
if SHAPE["gpu"] is not None or SHAPE["gpu_hours_authorised"]:
    raise RuntimeError("M2C Stage 0 authorises zero GPU hours; refusing to hold one")

# Copied, not aliased: M2C must not be able to change M1A's or M2's infra view.
# The infra keys -- volume, storage root, execution label, provenance root --
# stay M1A's, because they name where the frozen artifacts actually are. The
# SHAPE keys are overwritten from the filed record, because M1A's are a training
# phase's (A10G, 16 cores, 48 GiB, 24 h) and pricing this probe at them would
# report a threefold spend against a declaration it never breached.
MODAL_CONFIG = dict(M1A_CONFIG["modal"])
GPU = SHAPE["gpu"]
CPU = int(SHAPE["cpu"])
MEMORY_MB = int(SHAPE["memory_mb"])
TIMEOUT_SECONDS = int(SHAPE["timeout_seconds"])
MODAL_CONFIG.update(
    {"gpu": GPU, "cpu": CPU, "memory_mb": MEMORY_MB, "timeout_seconds": TIMEOUT_SECONDS}
)

STORAGE_ROOT = MODAL_CONFIG["storage_root"]
APP_NAME = "message-passing-retrieval-m2c-stage0-probe"
OUTPUT_PREFIX = "m2c_s4_structural_conditioning"
M2_OUTPUT_PREFIX = "m2_qls_v2_freeze"
M2B_OUTPUT_PREFIX = "m2b_semantic_minimality"

#: The rung whose weights Stage 0 reads, and the directory M2B stored it in.
#: M2B writes ``fit_root = cell_root / rung.lower()``, so the two differ in
#: case; on the container's filesystem that difference is a missing file.
S4_RUNG = "S4"
S4_FIT_DIRECTORY = S4_RUNG.lower()

#: One cell is one spawned call that writes its result once, at the end. A
#: restart therefore redoes exactly one cell and no more, and a re-spawn of a
#: finished cell returns its recorded result without recomputing it.
#: spawn_modal_jobs.py reads this to decide whether the piece a restart redoes
#: is one job or the whole probe; silence there is costed as no resumption.
RESUME_GRANULARITY = "cell"

app = modal.App(APP_NAME)
result_volume = modal.Volume.from_name(MODAL_CONFIG["result_volume"], create_if_missing=False)
image = (
    modal.Image.micromamba(python_version="3.11")
    .env(
        {
            "CONDA_OVERRIDE_CUDA": "12.1",
            "CUDA_HOME": "/opt/conda",
            "TORCH_CUDA_ARCH_LIST": "8.6",
            "PYTHONPATH": f"{REMOTE_ROOT}:{REMOTE_ROOT}/src",
        }
    )
    .apt_install("git", "build-essential", "ninja-build")
    .pip_install(
        "torch==2.2.1",
        "numpy<2.0",
        "scipy<1.14",
        "numba==0.60.0",
        "psutil==6.1.1",
        "pyyaml==6.0.2",
    )
    .pip_install(
        "torch-geometric==2.5.2",
        "torch-scatter==2.1.2",
        "torch-sparse==0.6.18",
        find_links="https://data.pyg.org/whl/torch-2.2.1+cu121.html",
    )
    .add_local_dir(str(RUNTIME_REPO_ROOT / "src"), remote_path=f"{REMOTE_ROOT}/src")
    .add_local_dir(str(RUNTIME_REPO_ROOT / "scripts"), remote_path=f"{REMOTE_ROOT}/scripts")
    .add_local_dir(str(RUNTIME_REPO_ROOT / "configs"), remote_path=f"{REMOTE_ROOT}/configs")
)


def compute_record() -> dict[str, Any]:
    """The filed Stage-0 compute record. Host-side only, and read on demand.

    On demand rather than at import because this module is imported inside the
    container too -- Modal loads it there to find ``run_stage0`` -- and the
    image carries no ``outputs/`` tree, so an import-time read would make every
    remote job die at startup. It is also read on demand so the module stays
    importable on a fresh clone, where the record has not been generated yet:
    the registry test imports every launcher, and a launcher that cannot be
    imported without a gitignored artifact is a launcher nobody can check.

    Absence is still refused at the moment it matters, in
    ``require_authorisation``, which is where a launch is actually decided.
    """

    if not COMPUTE_RECORD_PATH.is_file():
        raise SystemExit(
            f"{COMPUTE_RECORD_PATH} does not exist. The amendment makes a filed "
            "compute record a precondition of this launch; regenerate it with "
            "scripts/m2c_stage0_compute_record.py before submitting."
        )
    record = json.loads(COMPUTE_RECORD_PATH.read_text(encoding="utf-8"))
    if record["status"] != "FILED_BEFORE_LAUNCH":
        raise SystemExit(f"{COMPUTE_RECORD_PATH} is not a pre-launch record")
    if record["container"]["gpu"] is not None or record["container"]["gpu_hours_authorised"]:
        raise SystemExit("the filed record authorises zero GPU hours; refusing to hold one")
    container = record["container"]
    declared = (GPU, CPU, MEMORY_MB, TIMEOUT_SECONDS)
    filed = (
        container["gpu"],
        int(container["cpu"]),
        int(container["memory_mb"]),
        int(container["timeout_seconds"]),
    )
    if declared != filed:
        raise SystemExit(
            f"the declaration's container shape {declared} and the filed record's "
            f"{filed} disagree. They are written by one script; regenerate rather "
            "than reconcile them by hand."
        )
    return record


def _host_commit() -> str | None:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(HOST_REPO_ROOT),
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):  # pragma: no cover
        return None


def _validation_split_queries(dataset: str, confirmation: dict[str, Any]) -> int:
    """This dataset's validation split size, derived then cross-checked.

    The same derivation M2 and M2B used, and for the same reason: Stage 0 loads
    M2's sealed cell master under its build key, so it has to ask for the
    identical panel M2 scored. A different number here fails that check, which
    is the correct outcome but a wasteful way to find a transcription error.
    """

    measured = int(confirmation["data"]["splits"]["validation"])
    declared = M1A_CONFIG["datasets"].get(dataset, {}).get("validation_split_queries")
    if declared is not None and int(declared) != measured:
        raise ValueError(
            f"{dataset}: configs/m1a_feature_screen.yaml declares validation_split_queries="
            f"{declared} but its confirmation artifact's validation split holds {measured} "
            "queries -- resolve this before launching; Stage 0 reads M2's cell master for "
            "that split and cannot rebuild it"
        )
    return measured


def _m2_fits_root(dataset: str, fingerprint: str) -> PurePosixPath:
    """Where M2's headline run left this dataset's cell masters. Read-only.

    Masters live at ``<root>/<regime>/cell_features``, the layout
    run_m2_qls_v2_freeze.py wrote.
    """

    return (
        PurePosixPath(STORAGE_ROOT)
        / "outputs"
        / M2_OUTPUT_PREFIX
        / dataset
        / fingerprint[:16]
        / MODAL_CONFIG["execution_label"]
        / "headline"
        / "fits"
    )


def _m2b_fits_root(dataset: str, fingerprint: str) -> PurePosixPath:
    """Where M2B left this dataset's S4 checkpoints. Read-only.

    Checkpoints live at ``<root>/<regime>/<rung.lower()>/checkpoint.pt``, the
    layout run_m2b_semantic_minimality.py wrote -- lowercased, which is why the
    rung is not spelled as the declaration spells it. S4 is a CHALLENGER and S3
    remains M2B's frozen selection; reading S4's weights here changes neither.
    """

    return (
        PurePosixPath(STORAGE_ROOT)
        / "outputs"
        / M2B_OUTPUT_PREFIX
        / dataset
        / fingerprint[:16]
        / MODAL_CONFIG["execution_label"]
        / "headline"
        / "fits"
    )


def _jobs(datasets: list[str]) -> list[dict[str, Any]]:
    unknown = set(datasets) - set(CELLS)
    if unknown:
        raise ValueError(
            f"{sorted(unknown)} are not M2C Stage-0 cells; the declaration names "
            f"{sorted(CELLS)} and no others"
        )
    commit = _host_commit()
    # Per cell, because the record declares the admission panel as a total
    # across the four and the runner caps per job. Derived here rather than
    # restated so the two cannot drift, and carried in the job because the
    # container cannot read the record itself.
    record = compute_record()
    admission_cap = int(record["workload"]["admission_panel_total"]) // len(CELLS)
    jobs = []
    for dataset in datasets:
        settings = CONFIRMATION_CONFIG["datasets"][dataset]
        confirmation_path = HOST_REPO_ROOT / f"outputs/sa_mlp_confirmation/{dataset}.json"
        confirmation = json.loads(confirmation_path.read_text(encoding="utf-8"))
        if confirmation.get("status") != "SA_MLP_CONFIRMATION_DATASET_COMPLETE":
            raise ValueError(f"{confirmation_path} is not a complete confirmation artifact")
        fingerprint = confirmation["data_fingerprint_sha256"]
        jobs.append(
            {
                "dataset": dataset,
                "regime": CELLS[dataset],
                "fingerprint": fingerprint,
                "data_remote": confirmation["config"]["data"],
                "baseline": confirmation["baseline"],
                "expected_queries": int(confirmation["config"]["expected_queries"]),
                "validation_split_queries": _validation_split_queries(dataset, confirmation),
                "candidate_contract_compatibility": settings.get(
                    "candidate_contract_compatibility"
                ),
                "m2_fits_remote": str(_m2_fits_root(dataset, fingerprint)),
                "m2b_fits_remote": str(_m2b_fits_root(dataset, fingerprint)),
                "graph_root": str(
                    PurePosixPath(STORAGE_ROOT)
                    / MODAL_CONFIG["edge_provenance_root"]
                    / dataset
                    / fingerprint[:16]
                ),
                "admission_cap": admission_cap,
                "source_commit": commit,
            }
        )
    return jobs


def _active_modal_profile() -> str | None:
    """The profile this client will actually submit under, or None if unreadable.

    None rather than a guess, and the caller refuses on it: the wrong answer
    here sends a job to the wrong workspace, and a Modal volume lives in
    exactly one workspace.
    """

    from_env = os.environ.get("MODAL_PROFILE")
    if from_env:
        return from_env
    try:
        from modal.config import _profile
    except ImportError:  # pragma: no cover - modal always ships this
        return None
    return _profile or None


def execution_placement() -> dict[str, str]:
    """Which workspace each dataset runs on, from M2's declaration and only there.

    Inheriting is the point here rather than a shortcut. Stage 0 reads M2's cell
    masters and M2B's checkpoints, so a dataset can only be probed from the
    workspace whose volume holds them -- the one M2 ran it on. The map moves as
    workspaces reach their spend limits, so a second copy could only ever go
    stale; M2C declares no placement of its own for exactly that reason, and a
    copy appearing there later is refused rather than silently preferred.
    """

    copied = CONFIG.get("launch_authorization", {}).get("execution_placement")
    if copied:
        raise SystemExit(
            "configs/m2c_s4_structural_conditioning.yaml has grown its own "
            "execution_placement. The map is declared once, in "
            "configs/m2_qls_v2_freeze.yaml, and read at submit time; delete the copy."
        )
    inherited = M2_CONFIG["launch_authorization"].get("execution_placement")
    if not inherited:
        raise SystemExit(
            "configs/m2_qls_v2_freeze.yaml declares no workspace for these datasets; "
            "a dataset with no declared workspace cannot be submitted to one"
        )
    return dict(inherited)


def check_execution_placement(datasets: list[str]) -> dict[str, Any]:
    """Refuse to submit a dataset under a workspace its sealed artifacts are not on.

    scripts/spawn_modal_jobs.py calls this by name if a launcher defines it, so
    the check runs before the app is deployed and before anything is spawned.
    Stage 0 cannot rebuild a missing cell master or refit a missing checkpoint,
    so a misplaced job fails only after its container has started and been
    billed, having proved nothing.

    It is also where the declaration's gates are checked, because this is the
    only hook the server-side submission path calls before it deploys. A gate
    that only ``main`` consulted would be a gate the declared submission route
    walks straight past.
    """

    require_authorisation()
    placement = execution_placement()
    active = _active_modal_profile()
    if active is None:
        raise SystemExit(
            "cannot read the active Modal profile, so the workspace a job would land "
            "in is unknown. Set MODAL_PROFILE before importing modal."
        )
    undeclared = sorted(set(datasets) - set(placement))
    if undeclared:
        raise SystemExit(
            f"{undeclared} have no declared workspace in "
            "configs/m2_qls_v2_freeze.yaml#launch_authorization.execution_placement"
        )
    misplaced = {
        dataset: placement[dataset] for dataset in datasets if placement[dataset] != active
    }
    if misplaced:
        raise SystemExit(
            f"active profile {active!r} is not where these datasets' sealed artifacts "
            f"live: {misplaced}. Submit each dataset under its declared workspace."
        )
    return {"active_profile": active, "datasets": {d: placement[d] for d in datasets}}


def require_authorisation() -> None:
    """The declaration's gates, checked at call time rather than at import.

    At call time so this module stays importable -- and testable -- whatever the
    gates currently say, which is this track's standing order: commit the
    mechanism before the authorisation.
    """

    authorisation = CONFIG["launch_authorization"]
    if not authorisation["gates"].get("stage_0_compute_record_filed"):
        raise SystemExit(
            "configs/m2c_s4_structural_conditioning.yaml has not recorded a filed "
            "Stage-0 compute record. The record is the gate on this launch."
        )
    authorised = " ".join(authorisation["authorised_by_this_declaration"])
    if "Stage-0 Modal execution" not in authorised:
        raise SystemExit(
            "the declaration does not authorise Stage-0 Modal execution; refusing to spawn"
        )
    forbidden = {item.lower() for item in authorisation["not_authorised"]}
    if "learned transform training" not in forbidden:
        raise SystemExit(
            "the declaration no longer forbids learned-transform training, so this "
            "launcher can no longer assume the probe it spawns is the zero-training one"
        )
    # Last, because it is the expensive one and because its failure message is
    # about regenerating an artifact rather than about authorisation.
    compute_record()


def _output_root(job: dict[str, Any]) -> PurePosixPath:
    return (
        PurePosixPath(STORAGE_ROOT)
        / "outputs"
        / OUTPUT_PREFIX
        / "stage0"
        / job["dataset"]
        / job["fingerprint"][:16]
        / MODAL_CONFIG["execution_label"]
    )


def _runner_args(job: dict[str, Any]) -> argparse.Namespace:
    # The family A64 is defined on, and the value M2 recorded in this cell's
    # build key. Imported the way M2's own launcher imports it, and imported
    # rather than typed for a blunt reason: a different string here does not
    # mislabel the arm, it makes the sealed cell master refuse to load.
    from scripts.run_m0b_regime_map import MAINLINE_FAMILY

    regime = job["regime"]
    return argparse.Namespace(
        data=Path(job["data_remote"]),
        dataset=job["dataset"],
        regime=regime,
        data_fingerprint_sha256=job["fingerprint"],
        expected_queries=int(job["expected_queries"]),
        # The panel M2 scored, so the sealed master loads under its own build key.
        queries=int(job["validation_split_queries"]),
        baseline=job["baseline"],
        candidate_contract_compatibility=job["candidate_contract_compatibility"],
        cell_features=Path(job["m2_fits_remote"]) / regime / "cell_features",
        s4_checkpoint=(
            Path(job["m2b_fits_remote"]) / regime / S4_FIT_DIRECTORY / "checkpoint.pt"
        ),
        edge_provenance_root=Path(job["graph_root"]),
        output=Path(_output_root(job)) / f"{regime}.json",
        holdout_fraction=0.2,
        per_seed_cap=16,
        neighbour_scan_cap_per_seed=4096,
        a64_mainline_family=MAINLINE_FAMILY,
        dropout=0.2,
        temperature=0.07,
        panel_cap=0,
        admission_cap=int(job["admission_cap"]),
        source_commit=job.get("source_commit"),
    )


@app.function(
    image=image,
    volumes={STORAGE_ROOT: result_volume},
    timeout=TIMEOUT_SECONDS,
    cpu=CPU,
    memory=MEMORY_MB,
)
def run_stage0(job: dict[str, Any]) -> dict[str, Any]:
    os.chdir(REMOTE_ROOT)
    # Load-bearing: M2's masters, M2B's checkpoints and the provenance graphs
    # were written by other containers in other phases, so without this the
    # volume view is whatever it was when this container started.
    result_volume.reload()
    from scripts.run_m2c_stage0_probe import run

    args = _runner_args(job)
    result = run(args)
    result_volume.commit()
    return {
        "status": result["status"],
        "dataset": job["dataset"],
        "cell": result["cell"],
        "queries": result["panel"]["queries"],
        "trained_anything": result["trained_anything"],
        "test_split_read": result["test_split_read"],
        "output_remote": str(args.output),
    }


def _download(remote_path: str, local_path: Path) -> None:
    local_path.parent.mkdir(parents=True, exist_ok=True)
    relative = remote_path.removeprefix(f"{STORAGE_ROOT}/")
    with local_path.open("wb") as stream:
        for chunk in result_volume.read_file(relative):
            stream.write(chunk)


def fetch(datasets: str = ",".join(CELLS)) -> list[dict[str, Any]]:
    """Copy finished cell results down beside the declaration they answer.

    Separate from the spawn because the spawn is server-side and returns as soon
    as the calls are registered. Reads the volume; writes nothing to it.
    """

    requested = [name.strip() for name in datasets.split(",") if name.strip()]
    fetched = []
    local_root = HOST_REPO_ROOT / "outputs" / OUTPUT_PREFIX / "stage0"
    for job in _jobs(requested):
        remote = f"{_output_root(job)}/{job['regime']}.json"
        local = local_root / f"{job['dataset']}_{job['regime']}.json"
        _download(remote, local)
        fetched.append({"dataset": job["dataset"], "cell": f"{job['dataset']}/{job['regime']}",
                        "local": str(local)})
    return fetched


@app.local_entrypoint()
def main(datasets: str = ",".join(CELLS)) -> None:
    """A local fallback only. The declared submission path is server-side.

    scripts/spawn_modal_jobs.py deploys the app and spawns each job so the run
    outlives the client; this entrypoint exists so the app is complete and
    exercisable, and it refuses under the same gates.
    """

    requested = [name.strip() for name in datasets.split(",") if name.strip()]
    check_execution_placement(requested)
    results = list(run_stage0.map(_jobs(requested), return_exceptions=True))
    failures = [item for item in results if isinstance(item, BaseException)]
    if failures:
        raise RuntimeError(f"{len(failures)} M2C Stage-0 job(s) failed: {failures}")
    for result in results:
        _download(
            result["output_remote"],
            HOST_REPO_ROOT
            / "outputs"
            / OUTPUT_PREFIX
            / "stage0"
            / f"{result['cell'].replace('/', '_')}.json",
        )
    print(json.dumps(results, indent=2))
