"""Modal launcher for the frozen five-seed phase-crossover confirmation (E2).

``scripts/run_phase_confirmation.py`` refuses to run as ``__main__`` and directs
the caller to this launcher, so without it E2 has no execution path at all.

E2 is gated. ``configs/phase_confirmation.yaml`` is not written by hand: it is
generated by ``scripts/analyze_phase_screen.py`` from the locked validation-only
selection rule once the screen is complete. This module therefore loads that
config lazily and refuses to build jobs while it is absent, which is what keeps
a launch attempt before the gate from silently inventing rates.

Everything the container needs travels inside the job payload, so the generated
config is required on the launching machine only.
"""

from __future__ import annotations

import argparse
import json
import os
from collections.abc import Iterator, Mapping
from pathlib import Path, PurePosixPath
from typing import Any

import modal
import yaml

REMOTE_ROOT = "/root/message-passing-retrieval"
HOST_REPO_ROOT = Path(__file__).resolve().parents[1]
RUNTIME_REPO_ROOT = (
    HOST_REPO_ROOT
    if (HOST_REPO_ROOT / "configs" / "phase_screen.yaml").is_file()
    else Path(REMOTE_ROOT)
)
SCREEN_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "phase_screen.yaml"
FEATURE_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "sa_mlp_screen.yaml"
CONFIRMATION_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "phase_confirmation.yaml"

# The screen config is the ancestor of the confirmation config and always
# exists, so the container shape is known before the gate opens. The generated
# config carries the same block with only the app name replaced.
SCREEN_CONFIG = yaml.safe_load(SCREEN_CONFIG_PATH.read_text(encoding="utf-8"))
MODAL_CONFIG = SCREEN_CONFIG["modal"]
STORAGE_ROOT = MODAL_CONFIG["storage_root"]
APP_NAME = "message-passing-retrieval-phase-confirmation"

GATE_MESSAGE = (
    "configs/phase_confirmation.yaml does not exist yet.\n"
    "It is generated by scripts/analyze_phase_screen.py from the locked "
    "validation-only selection rule, and only once the phase screen is "
    "complete. Package E2 must not be launched before that gate: run the "
    "screen to completion, analyze it, commit the generated config, and tag "
    "the freeze first."
)


class _GatedConfig(Mapping):
    """The confirmation config, refused with an explanation until it is generated."""

    def _loaded(self) -> dict[str, Any]:
        if not CONFIRMATION_CONFIG_PATH.is_file():
            raise SystemExit(GATE_MESSAGE)
        config = yaml.safe_load(CONFIRMATION_CONFIG_PATH.read_text(encoding="utf-8"))
        declared = config.get("modal", {}).get("app")
        if declared != APP_NAME:
            raise SystemExit(
                f"Generated config names app {declared!r}, launcher deploys {APP_NAME!r}"
            )
        return config

    def __getitem__(self, key: str) -> Any:
        return self._loaded()[key]

    def __iter__(self) -> Iterator[str]:
        return iter(self._loaded())

    def __len__(self) -> int:
        return len(self._loaded())


CONFIG = _GatedConfig()

app = modal.App(APP_NAME)
result_volume = modal.Volume.from_name(MODAL_CONFIG["result_volume"], create_if_missing=False)
image = (
    modal.Image.micromamba(python_version="3.11")
    .env(
        {
            "CONDA_OVERRIDE_CUDA": "12.1",
            "CUDA_HOME": "/opt/conda",
            "TORCH_CUDA_ARCH_LIST": "8.6",
            "PYTHONPATH": f"{REMOTE_ROOT}:{REMOTE_ROOT}/src",
        }
    )
    .apt_install("git", "build-essential", "ninja-build")
    .pip_install(
        "torch==2.2.1",
        "numpy<2.0",
        "scipy<1.14",
        "numba==0.60.0",
        "psutil==6.1.1",
        "pyyaml==6.0.2",
    )
    .pip_install(
        "torch-geometric==2.5.2",
        "torch-scatter==2.1.2",
        "torch-sparse==0.6.18",
        find_links="https://data.pyg.org/whl/torch-2.2.1+cu121.html",
    )
    .add_local_dir(str(RUNTIME_REPO_ROOT / "src"), remote_path=f"{REMOTE_ROOT}/src")
    .add_local_dir(str(RUNTIME_REPO_ROOT / "scripts"), remote_path=f"{REMOTE_ROOT}/scripts")
    .add_local_file(
        str(SCREEN_CONFIG_PATH), remote_path=f"{REMOTE_ROOT}/configs/phase_screen.yaml"
    )
    .add_local_file(
        str(FEATURE_CONFIG_PATH), remote_path=f"{REMOTE_ROOT}/configs/sa_mlp_screen.yaml"
    )
)


def _rate_key(rate: float) -> str:
    return f"{rate:.2f}".replace(".", "p")


def _cell_root(kind: str, dataset: str, fingerprint: str, regime: str) -> PurePosixPath:
    return PurePosixPath(STORAGE_ROOT) / kind / dataset / fingerprint[:16] / regime


def _jobs(datasets: list[str]) -> list[dict[str, Any]]:
    config = CONFIG._loaded()
    training = config["training"]
    parameters = config["parameter_regime"]
    jobs: list[dict[str, Any]] = []
    for dataset in datasets:
        settings = config["datasets"][dataset]
        confirmation = json.loads(
            (HOST_REPO_ROOT / settings["confirmation"]).read_text(encoding="utf-8")
        )
        fingerprint = confirmation["data_fingerprint_sha256"]
        for axis, axis_config in config["axes"].items():
            for rate in axis_config["rates"]:
                # Rate zero is the clean condition. The runner refuses it: the
                # clean baseline reuses the sealed confirmation rather than
                # being retrained, so it is not an E2 cell.
                if float(rate) <= 0.0:
                    continue
                jobs.append(
                    {
                        "dataset": dataset,
                        "axis": axis,
                        "rate": float(rate),
                        "perturbation_seed": int(axis_config["perturbation_seed"]),
                        "expected_queries": int(settings["expected_queries"]),
                        "selected_gnn": settings["selected_gnn"],
                        "candidate_contract_compatibility": settings.get(
                            "candidate_contract_compatibility"
                        ),
                        "fingerprint": fingerprint,
                        "data_remote": confirmation["config"]["data"],
                        "clean_topology_cache": confirmation["config"]["topology_cache"],
                        "clean_feature_cache": confirmation["config"]["feature_cache"],
                        "baseline": confirmation["baseline"],
                        "seeds": [int(seed) for seed in training["seeds"]],
                        "epochs": int(training["epochs"]),
                        "batch_size": int(training["batch_size"]),
                        "learning_rate": float(training["learning_rate"]),
                        "weight_decay": float(training["weight_decay"]),
                        "ks": list(training["ks"]),
                        "layers": int(training["layers"]),
                        "dropout": float(training["dropout"]),
                        "temperature": float(training["temperature"]),
                        "hidden_dim": int(parameters["hidden_dim"]),
                        "projection_dim": int(parameters["projection_dim"]),
                        "max_parameter_difference": int(
                            parameters["maximum_sa_absolute_difference"]
                        ),
                        "inference_repeats": int(config["inference_repeats"]),
                    }
                )
    return jobs


def _runner_args(job: dict[str, Any]) -> argparse.Namespace:
    regime = f"{job['axis']}_{_rate_key(job['rate'])}"
    output_root = _cell_root(
        "outputs/phase_confirmation", job["dataset"], job["fingerprint"], regime
    )
    cache_root = _cell_root(
        "phase_confirmation_cache", job["dataset"], job["fingerprint"], regime
    )
    # E2 reuses the seed-0 validation checkpoint recorded by the screen cell for
    # exactly this dataset, axis and rate. The runner re-verifies that contract.
    screen_result = (
        _cell_root("outputs/phase_screen", job["dataset"], job["fingerprint"], regime)
        / "result.json"
    )
    # FEATURE_CONFIG_PATH resolves to the host repo locally and to the image
    # copy inside the container, so the args are inspectable before launch.
    screen = yaml.safe_load(FEATURE_CONFIG_PATH.read_text(encoding="utf-8"))
    return argparse.Namespace(
        data=Path(job["data_remote"]),
        dataset=job["dataset"],
        axis=job["axis"],
        rate=float(job["rate"]),
        perturbation_seed=int(job["perturbation_seed"]),
        expected_queries=int(job["expected_queries"]),
        output=Path(output_root) / "result.json",
        query_metrics_output=Path(output_root) / "query_metrics.npz",
        checkpoint_root=Path(output_root) / "checkpoints",
        screen_result=Path(screen_result),
        clean_topology_cache=Path(job["clean_topology_cache"]),
        clean_feature_cache=Path(job["clean_feature_cache"]),
        topology_cache=Path(cache_root) / "packed_topology_v1",
        feature_cache=Path(cache_root) / "fixed_structural_features_v1",
        baseline=job["baseline"],
        data_fingerprint_sha256=job["fingerprint"],
        selected_gnn=job["selected_gnn"],
        candidate_contract_compatibility=job["candidate_contract_compatibility"],
        seeds=[int(seed) for seed in job["seeds"]],
        # Read by _build_model, not by the runner's own body: omitting any of
        # these fails only once a container is already running.
        layers=int(job["layers"]),
        dropout=float(job["dropout"]),
        temperature=float(job["temperature"]),
        hidden_dim=int(job["hidden_dim"]),
        projection_dim=int(job["projection_dim"]),
        max_parameter_difference=int(job["max_parameter_difference"]),
        epochs=int(job["epochs"]),
        batch_size=int(job["batch_size"]),
        learning_rate=float(job["learning_rate"]),
        weight_decay=float(job["weight_decay"]),
        inference_repeats=int(job["inference_repeats"]),
        ks=list(job["ks"]),
        device="cuda",
        feature_config={
            "retrieval_seeds": screen["retrieval_seeds"],
            "static_features": screen["static_features"],
            "query_local_features": screen["query_local_features"],
            "preprocessing": {"query_chunk_size": 8192},
        },
    )


@app.function(
    image=image,
    gpu=MODAL_CONFIG["gpu"],
    volumes={STORAGE_ROOT: result_volume},
    timeout=MODAL_CONFIG["timeout_seconds"],
    cpu=MODAL_CONFIG["cpu"],
    memory=MODAL_CONFIG["memory_mb"],
)
def run_cell(job: dict[str, Any]) -> dict[str, Any]:
    os.chdir(REMOTE_ROOT)
    from scripts.run_phase_confirmation import run

    args = _runner_args(job)
    result = run(args, checkpoint_hook=result_volume.commit)
    return {
        "status": result["status"],
        "dataset": job["dataset"],
        "axis": job["axis"],
        "rate": job["rate"],
        "output_remote": str(args.output),
    }


@app.local_entrypoint()
def main(
    datasets: str = "2wiki_clean,musique_clean,webqsp,hotpotqa_clean,squad_clean,metaqa",
) -> None:
    requested = [name.strip() for name in datasets.split(",") if name.strip()]
    unknown = set(requested) - set(CONFIG["datasets"])
    if unknown:
        raise ValueError(f"Unregistered phase-confirmation datasets: {sorted(unknown)}")
    jobs = _jobs(requested)
    results = list(run_cell.map(jobs, return_exceptions=True, wrap_returned_exceptions=False))
    failures = [item for item in results if isinstance(item, BaseException)]
    if failures:
        raise RuntimeError(f"{len(failures)} phase-confirmation job(s) failed: {failures}")
    print(json.dumps(results, indent=2))
