"""Modal launcher for the M2D Stage-1 arm fits.

Four spawned jobs, one per declared Stage-1 cell. Each fits BOTH arms -- A1 and
A3-MINIMAL -- at seed 0, re-scores M2B's native S4 checkpoint on the same panel
without training it, and writes one immutable artifact per arm. Eight new fits
in total, which is exactly what section 5 authorises and no more.

Submit through scripts/spawn_modal_jobs.py so the run is server-side; a
detached local run is not a registered execution.

What differs from Stage 0's launcher
------------------------------------
Stage 0 trained nothing and refused to hold an accelerator. Stage 1 trains, so
the GPU refusal is INVERTED rather than inherited: this launcher refuses a
record that authorises no GPU, because a training phase priced without one has
not been priced.

The other difference is that a Stage-1 job's numbers only mean something if the
container scored what M2B scored. The runner enforces three identities and
refuses on each, but it can only check an expectation it is given, so the
expectations are computed HERE, host-side, from M2B's own filed headline
artifacts, and passed in. A job launched without them would still run and would
still produce artifacts; they would simply be uncomparable with the rows the
gate reads. So they are required, per cell, and their absence is a refusal at
submit time rather than a footnote in a result.

The container shape is not decided here. It is read from the compute record
filed before this launcher was allowed to run -- generated by
scripts/m2d_stage1_compute_record.py -- so a job cannot quietly acquire a
larger box than the filed prediction priced, and the spend gate in
spawn_modal_jobs.py prices the shape the container will actually hold.

The declared cells, the arms, the seed and the authorisation all come from
configs/m2d_s4_semantic_repair.yaml. This file restates none of them: a
launcher holding its own copy of the matrix can only ever disagree with the
thing that declared it.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path, PurePosixPath
from typing import Any

import modal
import yaml

REMOTE_ROOT = "/root/message-passing-retrieval"
HOST_REPO_ROOT = Path(__file__).resolve().parents[1]
RUNTIME_REPO_ROOT = (
    HOST_REPO_ROOT
    if (HOST_REPO_ROOT / "configs" / "m2d_s4_semantic_repair.yaml").is_file()
    else Path(REMOTE_ROOT)
)
M2D_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "m2d_s4_semantic_repair.yaml"
M2_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "m2_qls_v2_freeze.yaml"
M1A_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "m1a_feature_screen.yaml"
CONFIRMATION_CONFIG_PATH = RUNTIME_REPO_ROOT / "configs" / "sa_mlp_confirmation.yaml"
COMPUTE_RECORD_PATH = (
    RUNTIME_REPO_ROOT / "outputs" / "m2d_s4_semantic_repair" / "stage1_compute_record.json"
)

#: M2B's filed headline artifacts. Host-side only: the identity expectations
#: below are derived from them before anything is submitted, and the container
#: never reads them.
M2B_HEADLINE = HOST_REPO_ROOT / "outputs" / "m2b_semantic_minimality" / "headline"
BASELINE_TABLE = (
    HOST_REPO_ROOT / "outputs" / "m2c_s4_structural_conditioning" / "m2b_baseline_table.json"
)

M2D_CONFIG_TEXT = M2D_CONFIG_PATH.read_text(encoding="utf-8")
CONFIG = yaml.safe_load(M2D_CONFIG_TEXT)
M2_CONFIG = yaml.safe_load(M2_CONFIG_PATH.read_text(encoding="utf-8"))
M1A_CONFIG = yaml.safe_load(M1A_CONFIG_PATH.read_text(encoding="utf-8"))
CONFIRMATION_CONFIG = yaml.safe_load(CONFIRMATION_CONFIG_PATH.read_text(encoding="utf-8"))

#: The declaration's text, so every artifact this launch produces can say which
#: version of the protocol it was run under. Over the DECODED text rather than
#: the raw bytes, because the host reads this file with CRLF and the container
#: reads it with LF, and one declaration must not have two fingerprints
#: depending on which side asked.
CONFIG_FINGERPRINT = hashlib.sha256(M2D_CONFIG_TEXT.encode("utf-8")).hexdigest()

#: The four declared cells, read from the declaration. One dataset each, which
#: is what lets a job be addressed by dataset the way every other launcher in
#: this track is; a fifth cell on an already-listed dataset would break that,
#: and is refused here rather than discovered as an overwritten result.
_CELL_BLOCK = CONFIG["stage_1"]["cells"]
CELLS: dict[str, str] = {}
for _cell in (*_CELL_BLOCK["mandatory_blockers"], *_CELL_BLOCK["controls"]):
    _dataset, _regime = _cell.split("/")
    if _dataset in CELLS:
        raise RuntimeError(
            f"{_dataset} carries two declared Stage-1 cells; this launcher spawns one "
            "job per dataset and the second would overwrite the first"
        )
    CELLS[_dataset] = _regime

#: The two arms and the one seed, from the declaration rather than from here.
ARMS: tuple[str, ...] = tuple(CONFIG["stage_1"]["arms"])
SEEDS: list[int] = list(CONFIG["stage_1"]["seeds"])
if len(SEEDS) != 1:
    raise RuntimeError(f"Stage 1 declares seeds {SEEDS}; this launcher spawns one seed")
SEED = int(SEEDS[0])

# spawn_modal_jobs.py's shared package protocol validates --datasets against
# module.CONFIG["datasets"]. The alias satisfies that contract without adding a
# datasets key to the declaration's own schema.
CONFIG["datasets"] = CELLS

#: The container shape the compute record filed, taken from the declaration's
#: own copy of it. The generated record and this block are held equal by a
#: declaration test; this is the copy that is committed, and -- decisively --
#: the copy that exists inside the container, because the image carries src/,
#: scripts/ and configs/ and no outputs/ tree. The decorator below is evaluated
#: remotely as well as locally, so it can only read from something the
#: container has.
SHAPE = CONFIG["launch_authorization"]["stage_1_compute_record"]
if not SHAPE["gpu"]:
    raise RuntimeError(
        "M2D Stage 1 trains eight fits; a record that priced no accelerator has not "
        "priced this stage. Stage 0's zero-GPU refusal is inverted here, not inherited."
    )

# Copied, not aliased: M2D must not be able to change M1A's or M2's infra view.
# The infra keys -- volume, storage root, execution label -- stay M1A's, because
# they name where the frozen artifacts actually are. The SHAPE keys are
# overwritten from the filed record; for Stage 1 the GPU, cores and memory
# happen to equal M1A's, because the record deliberately prices the shape M2B's
# training seconds were measured on. The timeout does not: an hour is an abort
# criterion, and inheriting M1A's twenty-four would discard it.
MODAL_CONFIG = dict(M1A_CONFIG["modal"])
GPU = SHAPE["gpu"]
CPU = int(SHAPE["cpu"])
MEMORY_MB = int(SHAPE["memory_mb"])
TIMEOUT_SECONDS = int(SHAPE["timeout_seconds"])
MODAL_CONFIG.update(
    {"gpu": GPU, "cpu": CPU, "memory_mb": MEMORY_MB, "timeout_seconds": TIMEOUT_SECONDS}
)

STORAGE_ROOT = MODAL_CONFIG["storage_root"]
APP_NAME = "message-passing-retrieval-m2d-stage1-arms"
OUTPUT_PREFIX = "m2d_s4_semantic_repair"
STAGE_PREFIX = "stage1"
M2_OUTPUT_PREFIX = "m2_qls_v2_freeze"
M2B_OUTPUT_PREFIX = "m2b_semantic_minimality"
RUNNER_MODULE = "scripts.run_m2d_stage1_arms"

#: The frozen build key of the cell stores M2 sealed. M2D reads it; it never
#: sets it. Section 1 freezes the scored universe, and these are the fields
#: that identify it.
BUILD_KEY = M2_CONFIG["qls_universal"]["hyperparameters"]

#: The rung whose weights Stage 1 reads, and the directory M2B stored it in.
#: M2B writes ``fit_root = cell_root / rung.lower()``, so the two differ in
#: case; on the container's filesystem that difference is a missing file.
NATIVE_RUNG = "S4"

#: One cell is one spawned call that writes its two artifacts at the end. A
#: restart therefore redoes exactly one cell -- both arms -- and no more.
#: spawn_modal_jobs.py reads this to decide whether the piece a restart redoes
#: is one job or the whole stage; silence there is costed as no resumption.
RESUME_GRANULARITY = "cell"

app = modal.App(APP_NAME)
result_volume = modal.Volume.from_name(MODAL_CONFIG["result_volume"], create_if_missing=False)
image = (
    modal.Image.micromamba(python_version="3.11")
    .env(
        {
            "CONDA_OVERRIDE_CUDA": "12.1",
            "CUDA_HOME": "/opt/conda",
            "TORCH_CUDA_ARCH_LIST": "8.6",
            "PYTHONPATH": f"{REMOTE_ROOT}:{REMOTE_ROOT}/src",
        }
    )
    .apt_install("git", "build-essential", "ninja-build")
    .pip_install(
        "torch==2.2.1",
        "numpy<2.0",
        "scipy<1.14",
        "numba==0.60.0",
        "psutil==6.1.1",
        "pyyaml==6.0.2",
    )
    .pip_install(
        "torch-geometric==2.5.2",
        "torch-scatter==2.1.2",
        "torch-sparse==0.6.18",
        find_links="https://data.pyg.org/whl/torch-2.2.1+cu121.html",
    )
    .add_local_dir(str(RUNTIME_REPO_ROOT / "src"), remote_path=f"{REMOTE_ROOT}/src")
    .add_local_dir(str(RUNTIME_REPO_ROOT / "scripts"), remote_path=f"{REMOTE_ROOT}/scripts")
    .add_local_dir(str(RUNTIME_REPO_ROOT / "configs"), remote_path=f"{REMOTE_ROOT}/configs")
)


def compute_record() -> dict[str, Any]:
    """The filed Stage-1 compute record. Host-side only, and read on demand.

    On demand rather than at import because this module is imported inside the
    container too -- Modal loads it there to find ``run_stage1`` -- and the
    image carries no ``outputs/`` tree, so an import-time read would make every
    remote job die at startup. It is also read on demand so the module stays
    importable on a fresh clone, where the record has not been generated yet:
    the registry test imports every launcher, and a launcher that cannot be
    imported without a gitignored artifact is a launcher nobody can check.

    Absence is still refused at the moment it matters, in
    ``require_authorisation``, which is where a launch is actually decided.
    """

    if not COMPUTE_RECORD_PATH.is_file():
        raise SystemExit(
            f"{COMPUTE_RECORD_PATH} does not exist. A filed compute record is a "
            "precondition of this launch; regenerate it with "
            "scripts/m2d_stage1_compute_record.py before submitting."
        )
    record = json.loads(COMPUTE_RECORD_PATH.read_text(encoding="utf-8"))
    if not record.get("filed_before_any_job_was_submitted"):
        raise SystemExit(f"{COMPUTE_RECORD_PATH} is not a pre-launch record")
    # Inverted from Stage 0, which refused to hold an accelerator. Stage 1
    # trains; a record that authorises none has priced something else.
    if record["container"]["gpu"] is None or record.get("authorises_no_gpu"):
        raise SystemExit(
            "the filed record authorises no GPU, but Stage 1 fits eight models. "
            "Regenerate it rather than launching against a prediction for a "
            "different kind of job."
        )
    if record.get("trains_nothing"):
        raise SystemExit("the filed record says this stage trains nothing; it fits 8 models")
    container = record["container"]
    declared = (GPU, CPU, MEMORY_MB, TIMEOUT_SECONDS)
    filed = (
        container["gpu"],
        int(container["cpu_cores"]),
        int(container["memory_mb"]),
        int(container["timeout_seconds"]),
    )
    if declared != filed:
        raise SystemExit(
            f"the declaration's container shape {declared} and the filed record's "
            f"{filed} disagree. They are written by one script; regenerate rather "
            "than reconcile them by hand."
        )
    priced = {item["cell"] for item in record["workload"]["cells"]}
    declared_cells = {f"{dataset}/{regime}" for dataset, regime in CELLS.items()}
    if priced != declared_cells:
        raise SystemExit(
            f"the filed record prices {sorted(priced)} and the declaration names "
            f"{sorted(declared_cells)}. A job nobody priced is a job nobody authorised."
        )
    if int(record["workload"]["fits"]) != len(declared_cells) * len(ARMS):
        raise SystemExit(
            f"the filed record prices {record['workload']['fits']} fits and this "
            f"launcher spawns {len(declared_cells)} cells x {len(ARMS)} arms"
        )
    return record


def _host_commit() -> str | None:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=str(HOST_REPO_ROOT),
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):  # pragma: no cover
        return None


def _validation_split_queries(dataset: str, confirmation: dict[str, Any]) -> int:
    """This dataset's validation split size, derived then cross-checked.

    The same derivation M2, M2B, M2C and Stage 0 used, and for the same reason:
    Stage 1 loads M2's sealed cell master under its build key, so it has to ask
    for the identical panel M2 scored. A different number here fails that
    check, which is the correct outcome but a wasteful way to find a
    transcription error.
    """

    measured = int(confirmation["data"]["splits"]["validation"])
    declared = M1A_CONFIG["datasets"].get(dataset, {}).get("validation_split_queries")
    if declared is not None and int(declared) != measured:
        raise ValueError(
            f"{dataset}: configs/m1a_feature_screen.yaml declares validation_split_queries="
            f"{declared} but its confirmation artifact's validation split holds {measured} "
            "queries -- resolve this before launching; Stage 1 reads M2's cell master for "
            "that split and cannot rebuild it"
        )
    return measured


def panel_digest(query_ids: list[str]) -> str:
    """The runner's digest, imported rather than reimplemented.

    Two spellings of one hash is a bug that only ever shows up as an identity
    mismatch on a paid container, which is exactly the failure the identity
    check exists to prevent.
    """

    for path in (HOST_REPO_ROOT, HOST_REPO_ROOT / "src"):
        if str(path) not in sys.path:
            sys.path.insert(0, str(path))
    from scripts.run_m2d_stage1_arms import panel_digest as digest

    return digest(query_ids)


def _s4_seed_spread_pp(dataset: str, regime: str) -> tuple[float, str]:
    """The bound the native-S4 re-score must reproduce M2B's recall@5 within.

    Derived, never typed, and derived twice over because the table does not
    offer the same evidence for every cell.

    Where a cell has more than one filed seed -- the two blockers do -- the
    bound is that cell's OWN measured seed-to-seed spread, which is the gate's
    resolvable band and the most local statement available about how much this
    number moves when nothing meaningful changes.

    Where a cell has one seed -- both controls -- there is no per-cell
    measurement, so the bound is the largest S4 seed spread measured ANYWHERE
    in the filed table. That is looser, and it is labelled as looser in the job
    record rather than presented as the same kind of number.

    The check is deliberately generous either way. Its job is to catch a wrong
    panel, a wrong store or a wrong checkpoint, not to certify float
    reproducibility across devices; the panel digest and the shared-inputs hash
    are the tight checks, and they run first.
    """

    table = json.loads(BASELINE_TABLE.read_text(encoding="utf-8"))
    per_cell: dict[tuple[str, str], list[float]] = {}
    for row in table["rows"]:
        if row["rung"] != NATIVE_RUNG:
            continue
        per_cell.setdefault((row["dataset"], row["regime"]), []).append(row["recall@5"])

    values = per_cell.get((dataset, regime))
    if not values:
        raise ValueError(f"{dataset}/{regime} has no filed {NATIVE_RUNG} row to reproduce")
    if len(values) > 1:
        return (max(values) - min(values)) * 100.0, (
            f"this cell's own measured {NATIVE_RUNG} seed spread across "
            f"{len(values)} filed seeds"
        )
    spreads = [
        (max(seeds) - min(seeds)) * 100.0 for seeds in per_cell.values() if len(seeds) > 1
    ]
    if not spreads:
        raise ValueError(
            "no cell in the filed table has two seeds of "
            f"{NATIVE_RUNG}, so no reproduction bound can be derived from it"
        )
    return max(spreads), (
        f"this cell has one filed seed, so the bound is the largest {NATIVE_RUNG} seed "
        "spread measured anywhere in the table -- looser than a per-cell band, and "
        "labelled as such"
    )


def m2b_expectations(dataset: str, regime: str) -> dict[str, Any]:
    """What this container must reproduce, from M2B's own filed headline.

    Computed host-side and passed in, rather than looked up in the container,
    for two reasons. The volume holds M2B's fits but not its headline JSON, and
    more importantly an expectation the container derives for itself is an
    expectation the container can derive wrongly and then satisfy.
    """

    path = M2B_HEADLINE / f"{dataset}.json"
    if not path.is_file():
        raise FileNotFoundError(
            f"{path} does not exist, so there is nothing for {dataset}/{regime} to be "
            "compared against. Every Stage-1 delta is taken against M2B's filed rows; "
            "a cell whose filed row cannot be read cannot be launched."
        )
    payload = json.loads(path.read_text(encoding="utf-8"))
    block = payload["cells"][regime]
    rung = block["rungs"][NATIVE_RUNG]
    if int(rung["seed"]) != SEED:
        raise ValueError(
            f"{dataset}/{regime}: the filed {NATIVE_RUNG} row is seed {rung['seed']}, "
            f"and Stage 1 runs seed {SEED}"
        )
    bound_pp, bound_source = _s4_seed_spread_pp(dataset, regime)
    return {
        "panel_sha256": panel_digest(list(block["held_out_query_ids"])),
        "shared_inputs_sha256": block["shared_inputs"]["sha256"],
        "s4_recall_at_5": float(rung["metrics"]["recall@5"]),
        "s4_reproduction_bound_pp": bound_pp,
        "s4_reproduction_bound_source": bound_source,
        "held_out_queries": int(block["held_out_queries"]),
        "precomputed_width": int(block["precomputed_width"]),
        "filed_by": str(path.relative_to(HOST_REPO_ROOT)).replace("\\", "/"),
    }


def _m2_fits_root(dataset: str, fingerprint: str) -> PurePosixPath:
    """Where M2's headline run left this dataset's cell masters. Read-only.

    Masters live at ``<root>/<regime>/cell_features``, the layout
    run_m2_qls_v2_freeze.py wrote.
    """

    return (
        PurePosixPath(STORAGE_ROOT)
        / "outputs"
        / M2_OUTPUT_PREFIX
        / dataset
        / fingerprint[:16]
        / MODAL_CONFIG["execution_label"]
        / "headline"
        / "fits"
    )


def _m2b_fits_root(dataset: str, fingerprint: str) -> PurePosixPath:
    """Where M2B left this dataset's semantic checkpoints. Read-only.

    Checkpoints live at ``<root>/<regime>/<rung.lower()>/checkpoint.pt``, the
    layout run_m2b_semantic_minimality.py wrote -- lowercased, which is why the
    rung is not spelled here as the declaration spells it.
    """

    return (
        PurePosixPath(STORAGE_ROOT)
        / "outputs"
        / M2B_OUTPUT_PREFIX
        / dataset
        / fingerprint[:16]
        / MODAL_CONFIG["execution_label"]
        / "headline"
        / "fits"
    )


def _jobs(datasets: list[str]) -> list[dict[str, Any]]:
    unknown = set(datasets) - set(CELLS)
    if unknown:
        raise ValueError(
            f"{sorted(unknown)} are not M2D Stage-1 cells; the declaration names "
            f"{sorted(CELLS)} and no others"
        )
    commit = _host_commit()
    jobs = []
    for dataset in datasets:
        regime = CELLS[dataset]
        settings = CONFIRMATION_CONFIG["datasets"][dataset]
        confirmation_path = HOST_REPO_ROOT / f"outputs/sa_mlp_confirmation/{dataset}.json"
        confirmation = json.loads(confirmation_path.read_text(encoding="utf-8"))
        if confirmation.get("status") != "SA_MLP_CONFIRMATION_DATASET_COMPLETE":
            raise ValueError(f"{confirmation_path} is not a complete confirmation artifact")
        fingerprint = confirmation["data_fingerprint_sha256"]
        jobs.append(
            {
                "dataset": dataset,
                "regime": regime,
                "fingerprint": fingerprint,
                "data_remote": confirmation["config"]["data"],
                "baseline": confirmation["baseline"],
                "expected_queries": int(confirmation["config"]["expected_queries"]),
                # M1A's declared frozen width, read the way M2B's own launcher
                # reads it. Not from the confirmation artifact, which does not
                # carry it, and not typed: every parameter count in section 11
                # is a function of this number.
                "frozen_embedding_dim": int(
                    M1A_CONFIG["base"]["semantic_rung"]["frozen_embedding_dim"]
                ),
                "validation_split_queries": _validation_split_queries(dataset, confirmation),
                "candidate_contract_compatibility": settings.get(
                    "candidate_contract_compatibility"
                ),
                "m2_fits_remote": str(_m2_fits_root(dataset, fingerprint)),
                "m2b_fits_remote": str(_m2b_fits_root(dataset, fingerprint)),
                "expects": m2b_expectations(dataset, regime),
                "arms": list(ARMS),
                "seed": SEED,
                "config_fingerprint": CONFIG_FINGERPRINT,
                "source_commit": commit,
            }
        )
    return jobs


def _active_modal_profile() -> str | None:
    """The profile this client will actually submit under, or None if unreadable.

    None rather than a guess, and the caller refuses on it: the wrong answer
    here sends a job to the wrong workspace, and a Modal volume lives in
    exactly one workspace.
    """

    from_env = os.environ.get("MODAL_PROFILE")
    if from_env:
        return from_env
    try:
        from modal.config import _profile
    except ImportError:  # pragma: no cover - modal always ships this
        return None
    return _profile or None


def execution_placement() -> dict[str, str]:
    """Which workspace each dataset runs on, from M2's declaration and only there.

    Inheriting is the point here rather than a shortcut. Stage 1 reads M2's cell
    masters and M2B's checkpoints, so a cell can only be fit from the workspace
    whose volume holds them -- the one M2 ran it on. The map moves as workspaces
    reach their spend limits, so a second copy could only ever go stale; M2D
    declares no placement of its own for exactly that reason, and a copy
    appearing there later is refused rather than silently preferred.
    """

    copied = CONFIG.get("launch_authorization", {}).get("execution_placement")
    if copied:
        raise SystemExit(
            "configs/m2d_s4_semantic_repair.yaml has grown its own execution_placement. "
            "The map is declared once, in configs/m2_qls_v2_freeze.yaml, and read at "
            "submit time; delete the copy."
        )
    inherited = M2_CONFIG["launch_authorization"].get("execution_placement")
    if not inherited:
        raise SystemExit(
            "configs/m2_qls_v2_freeze.yaml declares no workspace for these datasets; "
            "a dataset with no declared workspace cannot be submitted to one"
        )
    return dict(inherited)


def check_execution_placement(datasets: list[str]) -> dict[str, Any]:
    """Refuse to submit a dataset under a workspace its sealed artifacts are not on.

    scripts/spawn_modal_jobs.py calls this by name if a launcher defines it, so
    the check runs before the app is deployed and before anything is spawned.
    Stage 1 cannot rebuild a missing cell master or refit a missing checkpoint,
    so a misplaced job fails only after its container has started and been
    billed, having proved nothing.

    It is also where the declaration's gates are checked, because this is the
    only hook the server-side submission path calls before it deploys. A gate
    that only ``main`` consulted would be a gate the declared submission route
    walks straight past.
    """

    require_authorisation()
    placement = execution_placement()
    active = _active_modal_profile()
    if active is None:
        raise SystemExit(
            "cannot read the active Modal profile, so the workspace a job would land "
            "in is unknown. Set MODAL_PROFILE before importing modal."
        )
    undeclared = sorted(set(datasets) - set(placement))
    if undeclared:
        raise SystemExit(
            f"{undeclared} have no declared workspace in "
            "configs/m2_qls_v2_freeze.yaml#launch_authorization.execution_placement"
        )
    misplaced = {
        dataset: placement[dataset] for dataset in datasets if placement[dataset] != active
    }
    if misplaced:
        raise SystemExit(
            f"active profile {active!r} is not where these datasets' sealed artifacts "
            f"live: {misplaced}. Submit each dataset under its declared workspace."
        )
    return {"active_profile": active, "datasets": {d: placement[d] for d in datasets}}


def require_authorisation() -> None:
    """The declaration's gates, checked at call time rather than at import.

    At call time so this module stays importable -- and testable -- whatever the
    gates currently say, which is this track's standing order: commit the
    mechanism before the authorisation.
    """

    authorisation = CONFIG["launch_authorization"]
    gates = authorisation["gates"]
    for gate in (
        "stage_0_advance_gate_evaluated",
        "stage_1_amendment_filed",
        "stage_1_authorised",
        "stage_1_gate_committed",
        "stage_1_compute_record_filed",
    ):
        if not gates.get(gate):
            raise SystemExit(
                f"configs/m2d_s4_semantic_repair.yaml has not earned {gate}. "
                "Every one of these is a precondition of this launch."
            )
    if CONFIG["stage_1"]["seeds"] != [SEED]:
        raise SystemExit(
            f"the declaration now names seeds {CONFIG['stage_1']['seeds']}; this "
            f"launcher spawns seed {SEED} only, and section 15 puts the extra seeds "
            "after the gate rather than beside it"
        )
    forbidden = {item.lower() for item in authorisation["not_authorised"]}
    if "seeds 1 and 2" not in forbidden or "the full 14-cell m2d screen" not in forbidden:
        raise SystemExit(
            "the declaration no longer restricts M2D to the seed-0 cells, so this "
            "launcher can no longer assume the eight fits it spawns are the whole "
            "authorised workload"
        )
    # Last, because it is the expensive one and because its failure message is
    # about regenerating an artifact rather than about authorisation.
    compute_record()


def _output_root(job: dict[str, Any]) -> PurePosixPath:
    """The run store this cell's artifacts are written INTO, not their paths.

    run_artifacts derives the rest -- phase, dataset, regime, arm, commit and
    run id -- so two submissions of the same cell cannot address one file.
    """

    return (
        PurePosixPath(STORAGE_ROOT)
        / "outputs"
        / OUTPUT_PREFIX
        / STAGE_PREFIX
        / job["dataset"]
        / job["fingerprint"][:16]
        / MODAL_CONFIG["execution_label"]
    )


def _runner_args(job: dict[str, Any]) -> argparse.Namespace:
    # The family A64 is defined on, and the value M2 recorded in this cell's
    # build key. Imported the way M2's own launcher imports it, and imported
    # rather than typed for a blunt reason: a different string here does not
    # mislabel the arm, it makes the sealed cell master refuse to load.
    from scripts.run_m0b_regime_map import MAINLINE_FAMILY

    regime = job["regime"]
    expects = job["expects"]
    return argparse.Namespace(
        data=Path(job["data_remote"]),
        dataset=job["dataset"],
        regime=regime,
        data_fingerprint_sha256=job["fingerprint"],
        expected_queries=int(job["expected_queries"]),
        frozen_embedding_dim=int(job["frozen_embedding_dim"]),
        # The panel M2 scored, so the sealed master loads under its own build key.
        queries=int(job["validation_split_queries"]),
        baseline=job["baseline"],
        candidate_contract_compatibility=job["candidate_contract_compatibility"],
        cell_features=Path(job["m2_fits_remote"]) / regime / "cell_features",
        s4_checkpoint=(
            Path(job["m2b_fits_remote"]) / regime / NATIVE_RUNG.lower() / "checkpoint.pt"
        ),
        arms=list(job["arms"]),
        seed=int(job["seed"]),
        # The three identities, derived host-side from M2B's filed headline.
        # Without these the container would still fit and still write, and the
        # artifacts would simply not be comparable with the rows the gate reads.
        expected_panel_sha256=expects["panel_sha256"],
        expected_shared_inputs_sha256=expects["shared_inputs_sha256"],
        expected_s4_recall_at_5=expects["s4_recall_at_5"],
        s4_reproduction_bound_pp=expects["s4_reproduction_bound_pp"],
        output_root=Path(_output_root(job)),
        config_fingerprint=job["config_fingerprint"],
        source_commit=job["source_commit"],
        run_id=None,
        fit_root=None,
        device=None,
        # M2B's training setup, which section 12 says not to reopen. Left at the
        # runner's defaults, which its own tests hold equal to M2B's parser and
        # to the values M2B's launcher actually passed.
        holdout_fraction=0.2,
        epochs=3,
        batch_size=16,
        dropout=0.2,
        temperature=0.07,
        learning_rate=1e-3,
        weight_decay=1e-4,
        latency_queries=200,
        latency_repeats=3,
        latency_warmup=8,
        # M2's frozen build key, read from its declaration rather than typed
        # here. These three decide whether the sealed master loads at all.
        per_seed_cap=int(BUILD_KEY["per_seed_cap"]),
        neighbour_scan_cap_per_seed=int(BUILD_KEY["neighbour_scan_cap_per_seed"]),
        a64_mainline_family=MAINLINE_FAMILY,
    )


@app.function(
    image=image,
    volumes={STORAGE_ROOT: result_volume},
    gpu=GPU,
    timeout=TIMEOUT_SECONDS,
    cpu=CPU,
    memory=MEMORY_MB,
)
def run_stage1(job: dict[str, Any]) -> dict[str, Any]:
    import importlib

    os.chdir(REMOTE_ROOT)
    # Load-bearing: M2's masters and M2B's checkpoints were written by other
    # containers in other phases, so without this the volume view is whatever
    # it was when this container started.
    result_volume.reload()
    run = importlib.import_module(RUNNER_MODULE).run

    result = run(_runner_args(job))
    result_volume.commit()
    return {
        "status": result["status"],
        "dataset": job["dataset"],
        "cell": result["cell"],
        "seed": result["seed"],
        "arms": result["arms"],
        "held_out_queries": result["held_out_queries"],
        "test_split_read": result["test_split_read"],
        "identity_checks": result["identity_checks"],
        "native_s4_reproduction": result["native_s4_reproduction"],
        "artifacts": {arm: receipt["path"] for arm, receipt in result["artifacts"].items()},
        "wall_seconds": result["wall_seconds"],
    }


def _staging_suffix(job: dict[str, Any], remote_path: str) -> PurePosixPath:
    """Where one physical run lands under the local staging directory.

    The identity segments and the filename, and nothing above them. What is
    dropped is the store prefix -- phase output root, dataset, data
    fingerprint, execution label -- which is constant for the cell and is
    already the directory being staged into, so mirroring it would say the
    same thing twice.

    That is not only tidiness. verify_artifact_file checks an artifact against
    its own location by comparing the LAST len(segments) directories, so the
    suffix kept here is exactly what that check reads; and the full remote path
    mirrored under the local root runs past Windows' 260-character limit, which
    is a fetch that fails on the host after the science has already succeeded.
    """

    return PurePosixPath(remote_path).relative_to(_output_root(job))


def _download(remote_path: str, local_path: Path) -> None:
    local_path.parent.mkdir(parents=True, exist_ok=True)
    relative = remote_path.removeprefix(f"{STORAGE_ROOT}/")
    with local_path.open("wb") as stream:
        for chunk in result_volume.read_file(relative):
            stream.write(chunk)


def _artifact_names() -> tuple[str, str]:
    """The phase and filename run_artifacts will have used.

    Imported here rather than at module scope on purpose. This module is
    imported inside the container as well as on the host, and only the fetch
    path needs the runner's constants; a module-level import would drag the
    whole scoring stack into every container at startup for the sake of two
    strings.
    """

    import importlib

    for path in (HOST_REPO_ROOT, HOST_REPO_ROOT / "src"):
        if str(path) not in sys.path:
            sys.path.insert(0, str(path))
    from mp_retrieval.run_artifacts import ARTIFACT_FILENAME

    return importlib.import_module(RUNNER_MODULE).PHASE, ARTIFACT_FILENAME


def _remote_prefix(job: dict[str, Any], arm: str) -> PurePosixPath:
    """One arm's logical result directory on the volume, above the physical runs.

    ``<phase>/<dataset>/<regime>/<seed>/<arm>`` -- run_artifacts orders its
    segments coarse to fine precisely so this prefix is listable. Stage 1 has
    two arms per cell, so unlike Stage 0 this is per arm rather than per job,
    and the seed segment is a real seed rather than ``no_seed``.
    """

    from mp_retrieval.run_artifacts import logical_segments

    # The segments are asked for rather than spelled. run_artifacts renders the
    # seed as "seed_0", and a launcher that wrote "seed0" would list an empty
    # prefix and report that a completed cell produced nothing -- which is what
    # the first version of this function did.
    phase, _ = _artifact_names()
    return _output_root(job).joinpath(
        *logical_segments(
            phase=phase,
            dataset=job["dataset"],
            regime=job["regime"],
            arm=arm,
            seed=int(job["seed"]),
        )
    )


def _remote_artifacts(prefix: PurePosixPath) -> list[str]:
    _, filename = _artifact_names()
    relative = str(prefix).removeprefix(f"{STORAGE_ROOT}/")
    found = []
    for entry in result_volume.listdir(relative, recursive=True):
        if PurePosixPath(entry.path).name == filename:
            found.append(f"{STORAGE_ROOT}/{entry.path}")
    return sorted(found)


def fetch(
    datasets: str = ",".join(CELLS), expect_source_commit: str = ""
) -> list[dict[str, Any]]:
    """Copy the selected result for each cell and arm down beside the declaration.

    Separate from the spawn because the spawn is server-side and returns as
    soon as the calls are registered. Reads the volume; writes nothing to it.

    The artifact path carries a run id the host did not choose, so the store is
    listed rather than guessed. Every physical run found is downloaded and
    verified, and then ONE is selected as the logical result -- by commit,
    stated by the caller, never by whichever file is newest. That is the whole
    point of the persistence work: a run that did not land leaves an older
    run's numbers in place, and a fetcher that took the newest file would
    report them without noticing.
    """

    if not expect_source_commit:
        raise SystemExit(
            "fetch needs the commit whose run is being reported. Selecting between "
            "physical runs is a decision, and a fetch that picked for itself would "
            "be free to report a run that was never meant to stand."
        )
    requested = [name.strip() for name in datasets.split(",") if name.strip()]
    fetched = []
    local_root = HOST_REPO_ROOT / "outputs" / OUTPUT_PREFIX / STAGE_PREFIX
    staging = local_root / "runs"
    from mp_retrieval import run_artifacts

    for job in _jobs(requested):
        cell = f"{job['dataset']}/{job['regime']}"
        for arm in job["arms"]:
            remotes = _remote_artifacts(_remote_prefix(job, arm))
            if not remotes:
                raise RuntimeError(
                    f"{cell} {arm}: the volume holds no artifact under its prefix"
                )
            receipts = []
            for remote in remotes:
                local = staging / _staging_suffix(job, remote)
                _download(remote, local)
                receipts.append(run_artifacts.verify_artifact_file(local))
            selected = run_artifacts.select_logical_result(
                receipts, expect_source_commit=expect_source_commit
            )
            destination = local_root / f"{job['dataset']}_{job['regime']}_{arm}.json"
            destination.write_bytes(Path(selected.path).read_bytes())
            fetched.append(
                {
                    "dataset": job["dataset"],
                    "cell": cell,
                    "arm": arm,
                    "local": str(destination),
                    "source_commit": selected.identity.source_commit,
                    "run_id": selected.identity.run_id,
                    "rows": selected.row_count,
                    "physical_runs_found": len(receipts),
                }
            )
    return fetched


@app.local_entrypoint()
def main(datasets: str = ",".join(CELLS)) -> None:
    """A local fallback only. The declared submission path is server-side.

    scripts/spawn_modal_jobs.py deploys the app and spawns each job so the run
    outlives the client; this entrypoint exists so the app is complete and
    exercisable, and it refuses under the same gates.
    """

    requested = [name.strip() for name in datasets.split(",") if name.strip()]
    check_execution_placement(requested)
    results = list(run_stage1.map(_jobs(requested), return_exceptions=True))
    failures = [item for item in results if isinstance(item, BaseException)]
    if failures:
        raise RuntimeError(f"{len(failures)} M2D Stage-1 job(s) failed: {failures}")
    print(json.dumps(results, indent=2))
